/**
 * AUTO-GENERATED by `pnpm --filter @ceo-agent/worker curate:bgm:cc0` — do not edit by hand.
 * CC0 (public domain, no attribution) BGM sourced from the Internet Archive.
 */
import type { BgmTrack } from "./library";

export const COMMERCIAL_BGM_LIBRARY: BgmTrack[] = [
  {
    "id": "luxury_piano",
    "name": "Luxury Piano",
    "category": "luxury",
    "durationSec": 180,
    "bpm": 72,
    "mood": "elegant",
    "tags": [
      "piano",
      "premium",
      "floral",
      "beauty"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-1/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.1%20-%2001%20The%20calling.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The calling\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "luxury_strings",
    "name": "Luxury Strings",
    "category": "luxury",
    "durationSec": 124,
    "bpm": 68,
    "mood": "soft",
    "tags": [
      "strings",
      "romantic",
      "boutique"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-2/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.2%20-%2001%20Morning's%20chill.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Morning's chill\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "luxury_ambient",
    "name": "Luxury Ambient",
    "category": "luxury",
    "durationSec": 88,
    "bpm": 72,
    "mood": "elegant",
    "tags": [
      "piano",
      "spa",
      "high-end"
    ],
    "fileUrl": "https://archive.org/download/komiku-cliff-road-chill/Komiku%20-%20Cliff%20Road%20Chill.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"Cliff Road Chill\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "luxury_soft_piano",
    "name": "Luxury Soft Piano",
    "category": "luxury",
    "durationSec": 159,
    "bpm": 70,
    "mood": "intimate",
    "tags": [
      "piano",
      "soft",
      "gift"
    ],
    "fileUrl": "https://archive.org/download/Komiku-the_binge_watchers/Komiku-TheBingeWatchers-Score1-01ActionIntroduction.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Komiku - The Binge Watchers - Score 1 - 01 Action Introduction\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "corporate_inspirational",
    "name": "Corporate Inspirational",
    "category": "corporate",
    "durationSec": 199,
    "bpm": 88,
    "mood": "confident",
    "tags": [
      "business",
      "trust",
      "property"
    ],
    "fileUrl": "https://archive.org/download/komiku-a-tale-is-never-forgotten/Komiku%20-%20A%20Tale%20is%20never%20forgotten%20-%2001%20The%20main%20reason%20we%20are%20here.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The main reason we are here\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "corporate_steady",
    "name": "Corporate Steady",
    "category": "corporate",
    "durationSec": 134,
    "bpm": 82,
    "mood": "stable",
    "tags": [
      "professional",
      "b2b",
      "finance"
    ],
    "fileUrl": "https://archive.org/download/komiku-animal-summer-music-camp/Komiku%20-%20Animal%20Summer%20Music%20Camp%20-%2001%20Time%20to%20live%20a%20musical%20adventure%20!.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Time to live a musical adventure !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "emotional_warm",
    "name": "Emotional Warm",
    "category": "emotional",
    "durationSec": 64,
    "bpm": 74,
    "mood": "heartfelt",
    "tags": [
      "emotional",
      "wedding",
      "family"
    ],
    "fileUrl": "https://archive.org/download/Komiku-HeliceAwesomeDanceAdventure/Komiku%20-%20Helice%20Awesome%20Dance%20Adventure%20!!%20-%2001%20An%20anarchist%20utopia.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"An anarchist utopia\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "inspirational_uplift",
    "name": "Inspirational Uplift",
    "category": "inspirational",
    "durationSec": 97,
    "bpm": 96,
    "mood": "uplifting",
    "tags": [
      "motivation",
      "growth",
      "education"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol1/Komiku%20-%20ULTRA%20PERSON%20VOL1%20-%2001%20Introduction%20to%20your%20adventure.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Introduction to your adventure\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cinematic_wide",
    "name": "Cinematic Wide",
    "category": "cinematic",
    "durationSec": 135,
    "bpm": 78,
    "mood": "epic",
    "tags": [
      "cinematic",
      "brand",
      "hero"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol2/Komiku_-_01_-_Level_4__First_infiltration_in_Unresponsible_Tech.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"Level 4 : First infiltration in Unresponsible Tech\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "modern_tech_pulse",
    "name": "Modern Tech Pulse",
    "category": "modern_tech",
    "durationSec": 116,
    "bpm": 104,
    "mood": "innovative",
    "tags": [
      "tech",
      "saas",
      "startup"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol3/Komiku_-_01_-_Level_7__Pogo_against_fascism.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Level 7 : Pogo against fascism\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "retail_upbeat",
    "name": "Upbeat Retail",
    "category": "retail_promotion",
    "durationSec": 187,
    "bpm": 110,
    "mood": "energetic",
    "tags": [
      "retail",
      "promo",
      "sale"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol4/Komiku%20-%20ULTRA%20PERSON%20VOL4%20-%2001%20Level%2010%20-%20Finally%20together.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Level 10 : Finally together\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "retail_promotion",
    "name": "Retail Promotion",
    "category": "retail_promotion",
    "durationSec": 45,
    "bpm": 108,
    "mood": "bright",
    "tags": [
      "shopping",
      "fashion",
      "deal"
    ],
    "fileUrl": "https://archive.org/download/Komiku-Poupis_incredible_adventures/Komiku-PoupisIncredibleAdventures-01Opening.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Opening !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "upbeat_energy",
    "name": "Upbeat Energy",
    "category": "upbeat",
    "durationSec": 62,
    "bpm": 118,
    "mood": "fun",
    "tags": [
      "fast",
      "social",
      "tiktok"
    ],
    "fileUrl": "https://archive.org/download/komiku-incredible-kart-game/Baseball%20music%20while%20waiting%20for%20online%20partners.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Baseball music while waiting for online partners\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "calm_ambient",
    "name": "Calm Warm",
    "category": "calm",
    "durationSec": 140,
    "bpm": 72,
    "mood": "warm",
    "tags": [
      "calm",
      "wellness",
      "soft",
      "cozy"
    ],
    "fileUrl": "https://archive.org/download/Komiku01ChildhoodScene/Komiku_-_01_-_Childhood_scene.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Childhood scene\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "storytelling_narrative",
    "name": "Storytelling Narrative",
    "category": "storytelling",
    "durationSec": 210,
    "bpm": 76,
    "mood": "narrative",
    "tags": [
      "story",
      "vlog",
      "journey"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-1/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.1%20-%2002%20On%20the%20tracks%20of%20the%20elders.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"On the tracks of the elders\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "florist_soft",
    "name": "Soft Floral",
    "category": "luxury",
    "durationSec": 162,
    "bpm": 70,
    "mood": "floral",
    "tags": [
      "florist",
      "flowers",
      "gift",
      "romantic"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-2/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.2%20-%2002%20The%20Ceremony.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The Ceremony\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cafe_upbeat",
    "name": "Upbeat Acoustic",
    "category": "upbeat",
    "durationSec": 164,
    "bpm": 105,
    "mood": "playful",
    "tags": [
      "cafe",
      "coffee",
      "lifestyle",
      "acoustic"
    ],
    "fileUrl": "https://archive.org/download/Komiku-the_binge_watchers/Komiku-TheBingeWatchers-Score1-05AmbiantShock.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Ambiant Shock\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "coffeehouse_calm",
    "name": "Coffeehouse",
    "category": "calm",
    "durationSec": 467,
    "bpm": 74,
    "mood": "cozy",
    "tags": [
      "cafe",
      "coffee",
      "cozy",
      "lifestyle"
    ],
    "fileUrl": "https://archive.org/download/komiku-a-tale-is-never-forgotten/Komiku%20-%20A%20Tale%20is%20never%20forgotten%20-%2002%20A%20forest%20for%20you%20and%20me.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"A forest for you and me\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "lifestyle_acoustic",
    "name": "Lifestyle Acoustic",
    "category": "calm",
    "durationSec": 128,
    "bpm": 82,
    "mood": "warm",
    "tags": [
      "lifestyle",
      "cafe",
      "boutique",
      "acoustic"
    ],
    "fileUrl": "https://archive.org/download/komiku-animal-summer-music-camp/Komiku%20-%20Animal%20Summer%20Music%20Camp%20-%2002%20Together%20to%20play%20!.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Together to play !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "modern_luxury_pop",
    "name": "Modern Luxury",
    "category": "modern_tech",
    "durationSec": 56,
    "bpm": 98,
    "mood": "premium",
    "tags": [
      "beauty",
      "salon",
      "spa",
      "modern"
    ],
    "fileUrl": "https://archive.org/download/Komiku-HeliceAwesomeDanceAdventure/Komiku%20-%20Helice%20Awesome%20Dance%20Adventure%20!!%20-%2002%20H%C3%A9lice's%20Theme.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Hélice's Theme\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_serene_dawn",
    "name": "Serene Dawn",
    "category": "calm",
    "durationSec": 154,
    "bpm": 70,
    "mood": "peaceful",
    "tags": [
      "calm",
      "morning",
      "soft"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol1/Komiku%20-%20ULTRA%20PERSON%20VOL1%20-%2002%20Level%201%20-%20Jump%20and%20shoot%20stuff%20101.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Level 1 : Jump and shoot stuff 101\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_gentle_breeze",
    "name": "Gentle Breeze",
    "category": "calm",
    "durationSec": 87,
    "bpm": 68,
    "mood": "relaxing",
    "tags": [
      "ambient",
      "spa",
      "wellness"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol2/Komiku_-_02_-_When_you_see_that_you_were_subject_of_experiment.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"When you see that you were subject of experiment\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_cozy_corner",
    "name": "Cozy Corner",
    "category": "calm",
    "durationSec": 161,
    "bpm": 72,
    "mood": "cozy",
    "tags": [
      "cafe",
      "lifestyle",
      "warm"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol3/Komiku_-_02_-_Boss_4__Cobblestone_in_their_face.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Boss 4 : Cobblestone in their face\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_soft_horizon",
    "name": "Soft Horizon",
    "category": "calm",
    "durationSec": 119,
    "bpm": 74,
    "mood": "dreamy",
    "tags": [
      "ambient",
      "soft",
      "background"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol4/Komiku%20-%20ULTRA%20PERSON%20VOL4%20-%2002%20We%20need%20a%20plan.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"We need a plan\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_morning_light",
    "name": "Morning Light",
    "category": "emotional",
    "durationSec": 109,
    "bpm": 76,
    "mood": "hopeful",
    "tags": [
      "emotional",
      "warm",
      "gentle"
    ],
    "fileUrl": "https://archive.org/download/Komiku-Poupis_incredible_adventures/Komiku-PoupisIncredibleAdventures-03TimeForTheWalkOfTheDay.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Time for the walk of the day\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_heartfelt_path",
    "name": "Heartfelt Path",
    "category": "emotional",
    "durationSec": 208,
    "bpm": 72,
    "mood": "tender",
    "tags": [
      "story",
      "family",
      "warm"
    ],
    "fileUrl": "https://archive.org/download/komiku-incredible-kart-game/Boss%20Fight%20Circuit.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Boss Fight Circuit\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_warm_embrace",
    "name": "Warm Embrace",
    "category": "emotional",
    "durationSec": 210,
    "bpm": 70,
    "mood": "heartfelt",
    "tags": [
      "romantic",
      "gift",
      "soft"
    ],
    "fileUrl": "https://archive.org/download/Komiku01ChildhoodScene/Komiku_-_02_-_The_first_person_crossing_the_bridge_since_a_century.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The first person crossing the bridge since a century\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_golden_hour",
    "name": "Golden Hour",
    "category": "emotional",
    "durationSec": 259,
    "bpm": 74,
    "mood": "nostalgic",
    "tags": [
      "sunset",
      "memory",
      "warm"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-1/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.1%20-%2003%20The%20urge%20of%20moving%2C%20smile%20on%20the%20faces.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The urge of moving, smile on the faces\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_rise_up",
    "name": "Rise Up",
    "category": "inspirational",
    "durationSec": 86,
    "bpm": 96,
    "mood": "uplifting",
    "tags": [
      "motivation",
      "growth",
      "positive"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-2/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.2%20-%2003%20Another%20day%20in%20the%20country%20side.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Another day in the country side\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_new_chapter",
    "name": "New Chapter",
    "category": "inspirational",
    "durationSec": 288,
    "bpm": 92,
    "mood": "hopeful",
    "tags": [
      "education",
      "startup",
      "bright"
    ],
    "fileUrl": "https://archive.org/download/Komiku-the_binge_watchers/Komiku-TheBingeWatchers-Score1-10AmbiantHope.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Ambiant Hope\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_forward_motion",
    "name": "Forward Motion",
    "category": "inspirational",
    "durationSec": 73,
    "bpm": 100,
    "mood": "driven",
    "tags": [
      "progress",
      "team",
      "energy"
    ],
    "fileUrl": "https://archive.org/download/komiku-a-tale-is-never-forgotten/Komiku%20-%20A%20Tale%20is%20never%20forgotten%20-%2003%20The%20sequence%20of%20everything.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The sequence of everything\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_skyward",
    "name": "Skyward",
    "category": "inspirational",
    "durationSec": 36,
    "bpm": 94,
    "mood": "aspiring",
    "tags": [
      "success",
      "achievement",
      "bright"
    ],
    "fileUrl": "https://archive.org/download/komiku-animal-summer-music-camp/Komiku%20-%20Animal%20Summer%20Music%20Camp%20-%2003%20Run%20!%20Because%20!.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Run ! Because !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_boardroom",
    "name": "Boardroom",
    "category": "corporate",
    "durationSec": 72,
    "bpm": 88,
    "mood": "professional",
    "tags": [
      "business",
      "b2b",
      "trust"
    ],
    "fileUrl": "https://archive.org/download/Komiku-HeliceAwesomeDanceAdventure/Komiku%20-%20Helice%20Awesome%20Dance%20Adventure%20!!%20-%2003%20I'm%20in%20the%20Not-a-Club.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"I'm in the Not-a-Club\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_steady_growth",
    "name": "Steady Growth",
    "category": "corporate",
    "durationSec": 107,
    "bpm": 84,
    "mood": "stable",
    "tags": [
      "finance",
      "corporate",
      "steady"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol1/Komiku%20-%20ULTRA%20PERSON%20VOL1%20-%2003%20Interview%20in%20a%20pub.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Interview in a pub\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_team_spirit",
    "name": "Team Spirit",
    "category": "corporate",
    "durationSec": 154,
    "bpm": 90,
    "mood": "confident",
    "tags": [
      "team",
      "office",
      "positive"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol2/Komiku_-_03_-_Level_5__Time_for_retribution.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Level 5 : Time for retribution\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_clear_vision",
    "name": "Clear Vision",
    "category": "corporate",
    "durationSec": 95,
    "bpm": 86,
    "mood": "focused",
    "tags": [
      "presentation",
      "strategy",
      "clean"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol3/Komiku_-_03_-_A_pint_of_rhum.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"A pint of rhum\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_grand_opening",
    "name": "Grand Opening",
    "category": "luxury",
    "durationSec": 122,
    "bpm": 72,
    "mood": "elegant",
    "tags": [
      "premium",
      "boutique",
      "spa"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol4/Komiku%20-%20ULTRA%20PERSON%20VOL4%20-%2003%20Boss%206%20-%20Swoop%20attack.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Boss 6 : Swoop attack\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_velvet_touch",
    "name": "Velvet Touch",
    "category": "luxury",
    "durationSec": 80,
    "bpm": 68,
    "mood": "refined",
    "tags": [
      "beauty",
      "salon",
      "soft"
    ],
    "fileUrl": "https://archive.org/download/Komiku-Poupis_incredible_adventures/Komiku-PoupisIncredibleAdventures-04TheWeeklyFair.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The weekly fair\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_pearl_glow",
    "name": "Pearl Glow",
    "category": "luxury",
    "durationSec": 42,
    "bpm": 70,
    "mood": "intimate",
    "tags": [
      "floral",
      "gift",
      "romantic"
    ],
    "fileUrl": "https://archive.org/download/komiku-incredible-kart-game/Choose%20your%20kart%20!.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Choose your kart !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_silk_road",
    "name": "Silk Road",
    "category": "luxury",
    "durationSec": 297,
    "bpm": 74,
    "mood": "sophisticated",
    "tags": [
      "high-end",
      "fashion",
      "elegant"
    ],
    "fileUrl": "https://archive.org/download/Komiku01ChildhoodScene/Komiku_-_03_-_Big_person_tiny_cities_world_maps_theme.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"Big person, tiny cities (world map's theme)\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_wide_lens",
    "name": "Wide Lens",
    "category": "cinematic",
    "durationSec": 163,
    "bpm": 78,
    "mood": "epic",
    "tags": [
      "cinematic",
      "hero",
      "brand"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-1/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.1%20-%2004%20Tonight%2C%20we%20feast%20!.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"Tonight, we feast !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_deep_story",
    "name": "Deep Story",
    "category": "cinematic",
    "durationSec": 162,
    "bpm": 76,
    "mood": "dramatic",
    "tags": [
      "narrative",
      "film",
      "wide"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-2/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.2%20-%2004%20The%20mini%20game.mp3",
    "brightness": "dark",
    "license": "royalty_free",
    "attribution": "\"The mini game\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_horizon_line",
    "name": "Horizon Line",
    "category": "cinematic",
    "durationSec": 149,
    "bpm": 80,
    "mood": "expansive",
    "tags": [
      "landscape",
      "travel",
      "epic"
    ],
    "fileUrl": "https://archive.org/download/Komiku-the_binge_watchers/Komiku-TheBingeWatchers-Score1-11ActionEpic.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"Action Epic\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_twilight_tale",
    "name": "Twilight Tale",
    "category": "cinematic",
    "durationSec": 272,
    "bpm": 74,
    "mood": "mysterious",
    "tags": [
      "moody",
      "story",
      "ambient"
    ],
    "fileUrl": "https://archive.org/download/komiku-a-tale-is-never-forgotten/Komiku%20-%20A%20Tale%20is%20never%20forgotten%20-%2004%20Walk%20in%20the%20forest.mp3",
    "brightness": "dark",
    "license": "royalty_free",
    "attribution": "\"Walk in the forest\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_digital_pulse",
    "name": "Digital Pulse",
    "category": "modern_tech",
    "durationSec": 96,
    "bpm": 104,
    "mood": "innovative",
    "tags": [
      "tech",
      "saas",
      "startup"
    ],
    "fileUrl": "https://archive.org/download/komiku-animal-summer-music-camp/Komiku%20-%20Animal%20Summer%20Music%20Camp%20-%2004%20Time%20to%20do%20some%20sport%20!.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Time to do some sport !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_future_wave",
    "name": "Future Wave",
    "category": "modern_tech",
    "durationSec": 116,
    "bpm": 108,
    "mood": "futuristic",
    "tags": [
      "ai",
      "digital",
      "modern"
    ],
    "fileUrl": "https://archive.org/download/Komiku-HeliceAwesomeDanceAdventure/Komiku%20-%20Helice%20Awesome%20Dance%20Adventure%20!!%20-%2004%20Everything%20is%20groovy%20(How%20to%20move%20your%20body).mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"Everything is groovy (How to move your body)\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_neon_drift",
    "name": "Neon Drift",
    "category": "modern_tech",
    "durationSec": 116,
    "bpm": 102,
    "mood": "sleek",
    "tags": [
      "app",
      "product",
      "clean"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol2/Komiku_-_04_-_Boss_2__Too_powerful_for_you_run_.mp3",
    "brightness": "neutral",
    "license": "royalty_free",
    "attribution": "\"Boss 2 : Too powerful for you, run !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_code_flow",
    "name": "Code Flow",
    "category": "modern_tech",
    "durationSec": 90,
    "bpm": 100,
    "mood": "focused",
    "tags": [
      "developer",
      "workspace",
      "tech"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol3/Komiku_-_04_-_Shopping_List.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Shopping List\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_shop_happy",
    "name": "Shop Happy",
    "category": "retail_promotion",
    "durationSec": 139,
    "bpm": 110,
    "mood": "bright",
    "tags": [
      "retail",
      "sale",
      "promo"
    ],
    "fileUrl": "https://archive.org/download/Komiku-ultra_person_vol4/Komiku%20-%20ULTRA%20PERSON%20VOL4%20-%2004%20The%20night%20before%20the%20fight%20of%20our%20life.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"The night before the fight of our life\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_flash_deal",
    "name": "Flash Deal",
    "category": "retail_promotion",
    "durationSec": 98,
    "bpm": 112,
    "mood": "energetic",
    "tags": [
      "shopping",
      "deal",
      "fast"
    ],
    "fileUrl": "https://archive.org/download/Komiku-Poupis_incredible_adventures/Komiku-PoupisIncredibleAdventures-05Surfing.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Surfing\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_weekend_sale",
    "name": "Weekend Sale",
    "category": "retail_promotion",
    "durationSec": 102,
    "bpm": 108,
    "mood": "fun",
    "tags": [
      "fashion",
      "mall",
      "promo"
    ],
    "fileUrl": "https://archive.org/download/komiku-incredible-kart-game/Country%20Circuit.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Country Circuit\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_boutique_pop",
    "name": "Boutique Pop",
    "category": "retail_promotion",
    "durationSec": 228,
    "bpm": 106,
    "mood": "playful",
    "tags": [
      "boutique",
      "lifestyle",
      "pop"
    ],
    "fileUrl": "https://archive.org/download/Komiku01ChildhoodScene/Komiku_-_04_-_Save_me_from_my_prison_heroic_principal_character.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Save me from my prison, heroic principal character\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_sunny_day",
    "name": "Sunny Day",
    "category": "upbeat",
    "durationSec": 257,
    "bpm": 118,
    "mood": "cheerful",
    "tags": [
      "social",
      "tiktok",
      "fun"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-1/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.1%20-%2005%20Sweet%20night%20and%20friends.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Sweet night and friends\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_jump_start",
    "name": "Jump Start",
    "category": "upbeat",
    "durationSec": 110,
    "bpm": 120,
    "mood": "energetic",
    "tags": [
      "fast",
      "dynamic",
      "youth"
    ],
    "fileUrl": "https://archive.org/download/komiku-the-adventure-goes-on-vol.-2/Komiku%20-%20The%20adventure%20goes%20on%2C%20vol.2%20-%2005%20Awkward%20cute%20dance.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Awkward cute dance\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_party_vibe",
    "name": "Party Vibe",
    "category": "upbeat",
    "durationSec": 90,
    "bpm": 116,
    "mood": "festive",
    "tags": [
      "event",
      "celebration",
      "bright"
    ],
    "fileUrl": "https://archive.org/download/Komiku-the_binge_watchers/Komiku-TheBingeWatchers-Score1-17ActionFight.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Action Fight\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_good_times",
    "name": "Good Times",
    "category": "upbeat",
    "durationSec": 272,
    "bpm": 114,
    "mood": "playful",
    "tags": [
      "lifestyle",
      "vlog",
      "happy"
    ],
    "fileUrl": "https://archive.org/download/komiku-a-tale-is-never-forgotten/Komiku%20-%20A%20Tale%20is%20never%20forgotten%20-%2005%20Fight%20in%20the%20forest.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Fight in the forest\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_road_trip",
    "name": "Road Trip",
    "category": "storytelling",
    "durationSec": 160,
    "bpm": 88,
    "mood": "adventurous",
    "tags": [
      "journey",
      "travel",
      "vlog"
    ],
    "fileUrl": "https://archive.org/download/komiku-animal-summer-music-camp/Komiku%20-%20Animal%20Summer%20Music%20Camp%20-%2005%20Pick%20an%20instrument%2C%20decorate%20it%20!.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Pick an instrument, decorate it !\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "id": "cc0_page_turner",
    "name": "Page Turner",
    "category": "storytelling",
    "durationSec": 104,
    "bpm": 82,
    "mood": "narrative",
    "tags": [
      "story",
      "blog",
      "warm"
    ],
    "fileUrl": "https://archive.org/download/Komiku-HeliceAwesomeDanceAdventure/Komiku%20-%20Helice%20Awesome%20Dance%20Adventure%20!!%20-%2005%20Captain%20Glouglou%20contest.mp3",
    "brightness": "warm",
    "license": "royalty_free",
    "attribution": "\"Captain Glouglou contest\" by Komiku (CC0 / Public Domain — no attribution required)",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
  }
];
