import { and, asc, eq, sql } from "drizzle-orm";
import { AiStoryDirectorPlanSchema, assertAiStoryDirectorPlanTransition, validateAiStoryDirectorPlan, type AiStoryDirectorPlan, type AiStoryDirectorSceneDirection } from "@ceo-agent/shared";
import { buildAiStoryDirectorPlan, computeAiStoryDirectorPlanFingerprint, computeAiStoryDirectorPlanSourceHash } from "@ceo-agent/shared/server";
import { getDb, schema } from "../client";
import type { AiStoryScriptScope } from "./ai-story-script";
type Db=ReturnType<typeof getDb>;
export class AiStoryDirectorPlanAuthorityError extends Error { constructor(readonly code:string,message:string){super(message);this.name="AiStoryDirectorPlanAuthorityError";} }
function parse(row:typeof schema.aiStoryDirectorPlanVersions.$inferSelect){return AiStoryDirectorPlanSchema.parse({...row.directorPlan,status:row.status,approvedBy:row.approvedBy,approvedAt:row.approvedAt?.toISOString()??null,frozenAt:row.frozenAt?.toISOString()??null});}
async function assertScope(db:Pick<Db,"execute">,scope:AiStoryScriptScope,mutation:boolean){const rows=await db.execute<{ok:boolean}>(sql`select exists(select 1 from ai_stories s join campaigns c on c.id=s.campaign_id join ai_story_versions v on v.story_id=s.id where s.id=${scope.storyId}::uuid and s.org_id=${scope.orgId}::uuid and s.workspace_id=${scope.workspaceId}::uuid and s.campaign_id=${scope.campaignId}::uuid and c.org_id=${scope.orgId}::uuid and c.workspace_id=${scope.workspaceId}::uuid and v.id=${scope.storyVersionId}::uuid and exists(select 1 from workspace_members wm where wm.workspace_id=${scope.workspaceId}::uuid and wm.user_id=${scope.actorUserId}::uuid and (${mutation}=false or wm.role in('admin','operator','editor','reviewer')))) as ok`);if(!rows[0]?.ok)throw new AiStoryDirectorPlanAuthorityError("DIRECTOR_SCOPE_DENIED","Director plan authority scope does not resolve");}

export class AiStoryDirectorPlanAuthorityService {
  constructor(private readonly db:Db=getDb()){}
  async propose(scope:AiStoryScriptScope,input:{handoffId:string;sceneDirections:AiStoryDirectorSceneDirection[];createdAt?:string}){
    return this.db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`director-plan:${scope.storyId}`}))`);await assertScope(tx,scope,true);
      const handoffRows=await tx.select().from(schema.aiStoryScriptDirectorHandoffs).where(and(eq(schema.aiStoryScriptDirectorHandoffs.handoffId,input.handoffId),eq(schema.aiStoryScriptDirectorHandoffs.orgId,scope.orgId),eq(schema.aiStoryScriptDirectorHandoffs.workspaceId,scope.workspaceId),eq(schema.aiStoryScriptDirectorHandoffs.storyId,scope.storyId),eq(schema.aiStoryScriptDirectorHandoffs.authorityStatus,"CURRENT"))).limit(1).for("share");
      if(!handoffRows[0])throw new AiStoryDirectorPlanAuthorityError("DIRECTOR_HANDOFF_NOT_CURRENT","Canonical Director plan requires the current frozen handoff");
      const handoff=handoffRows[0].handoff;
      const priorRows=await tx.select().from(schema.aiStoryDirectorPlanVersions).where(and(eq(schema.aiStoryDirectorPlanVersions.storyId,scope.storyId),eq(schema.aiStoryDirectorPlanVersions.status,"FROZEN"))).orderBy(asc(schema.aiStoryDirectorPlanVersions.version)).for("update");const prior=priorRows.at(-1);
      const plan=buildAiStoryDirectorPlan({handoff,sceneDirections:input.sceneDirections,version:(prior?.version??0)+1,supersedesDirectorPlanId:prior?.directorPlanId??null,createdBy:scope.actorUserId,createdAt:input.createdAt??new Date().toISOString()});
      const blocks=validateAiStoryDirectorPlan(plan,handoff,{expectedSourceHash:computeAiStoryDirectorPlanSourceHash(plan),expectedFingerprint:computeAiStoryDirectorPlanFingerprint(plan),currentHandoffId:handoff.handoffId}).filter(i=>i.severity==="BLOCK");
      if(blocks.length)throw new AiStoryDirectorPlanAuthorityError("DIRECTOR_PLAN_VALIDATION_FAILED",JSON.stringify(blocks));
      if(prior)await tx.update(schema.aiStoryDirectorPlanVersions).set({status:"SUPERSEDED"}).where(eq(schema.aiStoryDirectorPlanVersions.directorPlanId,prior.directorPlanId));
      await tx.insert(schema.aiStoryDirectorPlanVersions).values({directorPlanId:plan.directorPlanId,orgId:plan.orgId,workspaceId:plan.workspaceId,campaignId:scope.campaignId,storyId:plan.storyId,storyVersionId:plan.storyVersionId,outlineVersionId:plan.outlineVersionId,scriptVersionId:plan.scriptVersionId,handoffId:plan.handoffId,version:plan.version,contractVersion:plan.contractVersion,sourceHandoffFingerprint:plan.sourceHandoffFingerprint,sourceHash:plan.sourceHash,directorFingerprint:plan.directorFingerprint,status:plan.status,supersedesDirectorPlanId:plan.supersedesDirectorPlanId,directorPlan:plan,createdBy:plan.createdBy,createdAt:new Date(plan.createdAt)});return plan;
    });
  }
  async read(scope:AiStoryScriptScope,directorPlanId:string){await assertScope(this.db,scope,false);const rows=await this.db.select().from(schema.aiStoryDirectorPlanVersions).where(and(eq(schema.aiStoryDirectorPlanVersions.directorPlanId,directorPlanId),eq(schema.aiStoryDirectorPlanVersions.orgId,scope.orgId),eq(schema.aiStoryDirectorPlanVersions.workspaceId,scope.workspaceId),eq(schema.aiStoryDirectorPlanVersions.storyId,scope.storyId))).limit(1);if(!rows[0])throw new AiStoryDirectorPlanAuthorityError("DIRECTOR_PLAN_NOT_FOUND","Director plan not found in authority scope");return parse(rows[0]);}
  async history(scope:AiStoryScriptScope){await assertScope(this.db,scope,false);const rows=await this.db.select().from(schema.aiStoryDirectorPlanVersions).where(and(eq(schema.aiStoryDirectorPlanVersions.orgId,scope.orgId),eq(schema.aiStoryDirectorPlanVersions.workspaceId,scope.workspaceId),eq(schema.aiStoryDirectorPlanVersions.storyId,scope.storyId))).orderBy(asc(schema.aiStoryDirectorPlanVersions.version));return rows.map(parse);}
  async validate(scope:AiStoryScriptScope,directorPlanId:string){const plan=await this.read(scope,directorPlanId);const rows=await this.db.select().from(schema.aiStoryScriptDirectorHandoffs).where(eq(schema.aiStoryScriptDirectorHandoffs.handoffId,plan.handoffId)).limit(1);if(!rows[0])throw new AiStoryDirectorPlanAuthorityError("DIRECTOR_HANDOFF_NOT_FOUND","Bound handoff is missing");const issues=validateAiStoryDirectorPlan(plan,rows[0].handoff,{expectedSourceHash:computeAiStoryDirectorPlanSourceHash(plan),expectedFingerprint:computeAiStoryDirectorPlanFingerprint(plan),currentHandoffId:rows[0].handoffId});if(rows[0].authorityStatus!=="CURRENT")issues.push({gate:"STALE_DIRECTOR_PLAN_GATE",severity:"BLOCK",message:"Director plan is bound to a superseded handoff"});return issues;}
  async transition(scope:AiStoryScriptScope,directorPlanId:string,to:"VALIDATED"|"APPROVED"|"FROZEN",at=new Date().toISOString()){
    return this.db.transaction(async tx=>{await assertScope(tx,scope,true);const rows=await tx.select().from(schema.aiStoryDirectorPlanVersions).where(and(eq(schema.aiStoryDirectorPlanVersions.directorPlanId,directorPlanId),eq(schema.aiStoryDirectorPlanVersions.orgId,scope.orgId),eq(schema.aiStoryDirectorPlanVersions.workspaceId,scope.workspaceId))).limit(1).for("update");if(!rows[0])throw new AiStoryDirectorPlanAuthorityError("DIRECTOR_PLAN_NOT_FOUND","Director plan not found");const plan=parse(rows[0]);assertAiStoryDirectorPlanTransition(plan.status,to);if(to==="VALIDATED"){const handoffs=await tx.select().from(schema.aiStoryScriptDirectorHandoffs).where(eq(schema.aiStoryScriptDirectorHandoffs.handoffId,plan.handoffId)).limit(1);if(!handoffs[0]||validateAiStoryDirectorPlan(plan,handoffs[0].handoff,{expectedSourceHash:computeAiStoryDirectorPlanSourceHash(plan),expectedFingerprint:computeAiStoryDirectorPlanFingerprint(plan),currentHandoffId:handoffs[0].authorityStatus==="CURRENT"?handoffs[0].handoffId:undefined}).some(i=>i.severity==="BLOCK"))throw new AiStoryDirectorPlanAuthorityError("DIRECTOR_PLAN_VALIDATION_FAILED","Director plan failed deterministic gates");}
      const next:AiStoryDirectorPlan={...plan,status:to,approvedBy:to==="APPROVED"?scope.actorUserId:plan.approvedBy,approvedAt:to==="APPROVED"?at:plan.approvedAt,frozenAt:to==="FROZEN"?at:plan.frozenAt};await tx.update(schema.aiStoryDirectorPlanVersions).set({status:to,directorPlan:next,approvedBy:next.approvedBy,approvedAt:next.approvedAt?new Date(next.approvedAt):null,frozenAt:next.frozenAt?new Date(next.frozenAt):null}).where(eq(schema.aiStoryDirectorPlanVersions.directorPlanId,directorPlanId));return next;});
  }
}
