import { and, asc, eq, inArray, sql } from "drizzle-orm";
import { AiStoryDirectorPlanSchema, AiStoryMotionPlanSchema, AiStoryOutlineVersionSchema, AiStoryPreGenerationQcEvaluationSchema, AiStoryScriptDirectorHandoffSchema, AiStoryScriptVersionSchema } from "@ceo-agent/shared";
import { assertAiStoryPreGenerationQcCurrent, evaluateAiStoryPreGenerationQc, validateAiStoryPreGenerationQcFingerprint, type AiStoryPreGenerationQcInput } from "@ceo-agent/shared/server";
import { getDb } from "../client";
import * as schema from "../schema";
import type { AiStoryScriptScope } from "./ai-story-script";

type Db=ReturnType<typeof getDb>;
export class AiStoryPreGenerationQcAuthorityError extends Error { constructor(readonly code:string,message:string){super(message);this.name="AiStoryPreGenerationQcAuthorityError";} }
async function assertScope(tx:any,scope:AiStoryScriptScope,write=false){const rows=await tx.select().from(schema.aiStories).where(and(eq(schema.aiStories.id,scope.storyId),eq(schema.aiStories.workspaceId,scope.workspaceId),eq(schema.aiStories.campaignId,scope.campaignId))).limit(1);if(!rows[0])throw new AiStoryPreGenerationQcAuthorityError("QC_SCOPE_DENIED","Story is outside the requested scope");const members=await tx.select().from(schema.workspaceMembers).where(and(eq(schema.workspaceMembers.workspaceId,scope.workspaceId),eq(schema.workspaceMembers.userId,scope.actorUserId))).limit(1);if(!members[0]||(write&&!['admin','operator','editor','reviewer'].includes(members[0].role)))throw new AiStoryPreGenerationQcAuthorityError("QC_AUTHORIZATION_DENIED","Workspace authority denied");}

export class AiStoryPreGenerationQcAuthorityService {
  constructor(private readonly db:Db=getDb()){}
  async evaluate(scope:AiStoryScriptScope,input:{motionPlanId:string;providerCapability:AiStoryPreGenerationQcInput["providerCapability"];compilationRequest:AiStoryPreGenerationQcInput["compilationRequest"];evaluatedAt?:string}){return this.db.transaction(async tx=>{
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`pregen-qc:${input.compilationRequest.sceneExecutionId}`}))`);await assertScope(tx,scope,true);
    const motions=await tx.select().from(schema.aiStoryMotionPlanVersions).where(and(eq(schema.aiStoryMotionPlanVersions.motionPlanId,input.motionPlanId),eq(schema.aiStoryMotionPlanVersions.workspaceId,scope.workspaceId))).limit(1).for("share");if(!motions[0])throw new AiStoryPreGenerationQcAuthorityError("QC_MOTION_NOT_FOUND","Motion authority not found");const m=motions[0];
    const [directors,handoffs,scripts,outlines]=await Promise.all([tx.select().from(schema.aiStoryDirectorPlanVersions).where(eq(schema.aiStoryDirectorPlanVersions.directorPlanId,m.directorPlanId)).limit(1),tx.select().from(schema.aiStoryScriptDirectorHandoffs).where(eq(schema.aiStoryScriptDirectorHandoffs.handoffId,m.handoffId)).limit(1),tx.select().from(schema.aiStoryScriptVersions).where(eq(schema.aiStoryScriptVersions.scriptVersionId,m.scriptVersionId)).limit(1),tx.select().from(schema.aiStoryOutlineVersions).where(eq(schema.aiStoryOutlineVersions.outlineVersionId,m.outlineVersionId)).limit(1)]);if(!directors[0]||!handoffs[0]||!scripts[0]||!outlines[0])throw new AiStoryPreGenerationQcAuthorityError("QC_LINEAGE_MISSING","Frozen creative lineage is incomplete");
    const outline=AiStoryOutlineVersionSchema.parse({...outlines[0].outline,status:outlines[0].status,approvedBy:outlines[0].approvedBy,approvedAt:outlines[0].approvedAt?.toISOString()??null,frozenAt:outlines[0].frozenAt?.toISOString()??null});const script=AiStoryScriptVersionSchema.parse({...scripts[0].script,status:scripts[0].status,approvedBy:scripts[0].approvedBy,approvedAt:scripts[0].approvedAt?.toISOString()??null,frozenAt:scripts[0].frozenAt?.toISOString()??null});const handoff=AiStoryScriptDirectorHandoffSchema.parse(handoffs[0].handoff);const directorPlan=AiStoryDirectorPlanSchema.parse({...directors[0].directorPlan,status:directors[0].status,approvedBy:directors[0].approvedBy,approvedAt:directors[0].approvedAt?.toISOString()??null,frozenAt:directors[0].frozenAt?.toISOString()??null});const motionPlan=AiStoryMotionPlanSchema.parse({...m.motionPlan,status:m.status,approvedBy:m.approvedBy,approvedAt:m.approvedAt?.toISOString()??null,frozenAt:m.frozenAt?.toISOString()??null});
    const sourceAssetIds=handoff.productAuthorityBindings.map(b=>b.sourceAssetId);const assets=sourceAssetIds.length?await tx.select({id:schema.assets.id,contentHash:schema.assets.contentHash}).from(schema.assets).where(inArray(schema.assets.id,sourceAssetIds)):[];const byId=new Map(assets.map(a=>[a.id,a]));const productAuthority=handoff.productAuthorityBindings.map(b=>({productAuthorityId:b.productAuthorityId,sourceAssetId:b.sourceAssetId,sourceAssetContentHash:byId.get(b.sourceAssetId)?.contentHash??"sha256:"+"0".repeat(64)}));const known=new Set([...script.authorityReferences.map(r=>`${r.authorityType}:${r.authorityId}`),...handoff.productAuthorityBindings.map(b=>`ASSET:${b.sourceAssetId}`)]);
    const evaluation=evaluateAiStoryPreGenerationQc({outline,script,handoff,directorPlan,motionPlan,productAuthority,providerCapability:input.providerCapability,compilationRequest:input.compilationRequest,currentAuthority:{outlineVersionId:outline.outlineVersionId,scriptVersionId:script.scriptVersionId,handoffId:handoff.handoffId,directorPlanId:directorPlan.directorPlanId,motionPlanId:motionPlan.motionPlanId},knownAuthorityReferences:known,evaluatedBy:scope.actorUserId,evaluatedAt:input.evaluatedAt??new Date().toISOString()});const prior=await tx.select().from(schema.aiStoryPreGenerationQcEvaluations).where(eq(schema.aiStoryPreGenerationQcEvaluations.sceneExecutionId,evaluation.sceneExecutionId)).orderBy(asc(schema.aiStoryPreGenerationQcEvaluations.evaluationVersion));const existing=prior.find(r=>r.qcFingerprint===evaluation.qcFingerprint);if(existing)return AiStoryPreGenerationQcEvaluationSchema.parse(existing.evaluation);
    await tx.insert(schema.aiStoryPreGenerationQcEvaluations).values({qcEvaluationId:evaluation.qcEvaluationId,orgId:evaluation.orgId,workspaceId:evaluation.workspaceId,campaignId:scope.campaignId,storyId:evaluation.storyId,storyVersionId:evaluation.storyVersionId,outlineVersionId:evaluation.outlineVersionId,scriptVersionId:evaluation.scriptVersionId,handoffId:evaluation.handoffId,directorPlanId:evaluation.directorPlanId,motionPlanId:evaluation.motionPlanId,sceneExecutionId:evaluation.sceneExecutionId,evaluationVersion:prior.length+1,contractVersion:evaluation.contractVersion,gateSetVersion:evaluation.gateSetVersion,providerCapabilityId:evaluation.providerCapabilityId,providerCapabilityVersion:evaluation.providerCapabilityVersion,dispatchDecision:evaluation.dispatchDecision,qcFingerprint:evaluation.qcFingerprint,evaluation,evaluatedBy:evaluation.evaluatedBy,evaluatedAt:new Date(evaluation.evaluatedAt)});return evaluation;
  });}
  async read(scope:AiStoryScriptScope,qcEvaluationId:string){await assertScope(this.db,scope);const rows=await this.db.select().from(schema.aiStoryPreGenerationQcEvaluations).where(and(eq(schema.aiStoryPreGenerationQcEvaluations.qcEvaluationId,qcEvaluationId),eq(schema.aiStoryPreGenerationQcEvaluations.workspaceId,scope.workspaceId))).limit(1);if(!rows[0])throw new AiStoryPreGenerationQcAuthorityError("QC_NOT_FOUND","QC evaluation not found");return AiStoryPreGenerationQcEvaluationSchema.parse(rows[0].evaluation);}
  async history(scope:AiStoryScriptScope,sceneExecutionId:string){await assertScope(this.db,scope);const rows=await this.db.select().from(schema.aiStoryPreGenerationQcEvaluations).where(and(eq(schema.aiStoryPreGenerationQcEvaluations.sceneExecutionId,sceneExecutionId),eq(schema.aiStoryPreGenerationQcEvaluations.workspaceId,scope.workspaceId))).orderBy(asc(schema.aiStoryPreGenerationQcEvaluations.evaluationVersion));return rows.map(r=>AiStoryPreGenerationQcEvaluationSchema.parse(r.evaluation));}
  async assertCurrent(scope:AiStoryScriptScope,qcEvaluationId:string){const evaluation=await this.read(scope,qcEvaluationId);const motions=await this.db.select().from(schema.aiStoryMotionPlanVersions).where(eq(schema.aiStoryMotionPlanVersions.motionPlanId,evaluation.motionPlanId)).limit(1);if(!motions[0]||motions[0].status!=="FROZEN")throw new AiStoryPreGenerationQcAuthorityError("STALE_QC","QC cannot authorize dispatch from stale Motion authority");assertAiStoryPreGenerationQcCurrent(evaluation,{outlineVersionId:motions[0].outlineVersionId,scriptVersionId:motions[0].scriptVersionId,handoffId:motions[0].handoffId,directorPlanId:motions[0].directorPlanId,motionPlanId:motions[0].motionPlanId});if(!validateAiStoryPreGenerationQcFingerprint(evaluation))throw new AiStoryPreGenerationQcAuthorityError("QC_FINGERPRINT_MISMATCH","QC evidence fingerprint mismatch");return evaluation;}
}
