import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  AI_STORY_PRE_GENERATION_QC_GATE_ORDER,
  AiStorySceneMotionPlanSchema,
  preGenerationQcAllowsDispatch,
  projectLegacyStoryToPreGenerationQcCompatibility,
  type AiStoryDirectorPlan,
  type AiStoryMotionPlan,
  type AiStoryOutlineVersion,
  type AiStoryScriptDirectorHandoff,
  type AiStoryScriptVersion,
} from "@ceo-agent/shared";
import {
  assertAiStoryPreGenerationDispatchEligible,
  assertAiStoryPreGenerationQcCurrent,
  buildAiStoryDirectorPlan,
  buildAiStoryMotionPlan,
  buildAiStoryOutlineVersion,
  buildAiStoryScriptDirectorHandoff,
  buildAiStoryScriptVersion,
  evaluateAiStoryPreGenerationQc,
  validateAiStoryPreGenerationQcFingerprint,
} from "@ceo-agent/shared/server";

const id=(n:number)=>`84000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;
const assetHash=`sha256:${"b".repeat(64)}`;
const I={org:id(1),workspace:id(2),story:id(3),storyVersion:id(4),unit:id(5),beatA:id(6),beatB:id(7),sceneA:id(8),sceneB:id(9),entryA:id(10),entryB:id(11),actor:id(12),a:id(13),b:id(14),product:id(15),shotA:id(16),shotB:id(17),directorSceneA:id(18),directorSceneB:id(19),blockingA:id(20),blockingB:id(21),sceneExecution:id(22)};
const frozen=<T extends {status:string;approvedBy:string|null;approvedAt:string|null;frozenAt:string|null}>(value:T):T=>({...value,status:"FROZEN",approvedBy:I.actor,approvedAt:"2026-08-29T04:00:00.000Z",frozenAt:"2026-08-29T04:01:00.000Z"});

function outline():AiStoryOutlineVersion{return frozen(buildAiStoryOutlineVersion({storyId:I.story,storyVersionId:I.storyVersion,orgId:I.org,workspaceId:I.workspace,version:1,profile:{profileId:"CORE",profileVersion:1},premise:"A transfer reveals dependable product evidence",coreClaim:"Human context and detail establish confidence",storyUnits:[{storyUnitId:I.unit,order:0,purpose:"Complete story",summary:"Transfer then inspect",requiredBeatIds:[I.beatA,I.beatB]}],beats:[{id:I.beatA,storyUnitId:I.unit,order:0,classification:"MAJOR",name:"Transfer",purpose:"Establish relationship",summary:"A transfers Product to B",required:true,ownershipPolicy:"EXCLUSIVE",authorityReferences:[{authorityType:"PRODUCT",authorityId:I.product}]},{id:I.beatB,storyUnitId:I.unit,order:1,classification:"MAJOR",name:"Evidence",purpose:"Reveal evidence",summary:"B reveals a distinct detail",required:true,ownershipPolicy:"EXCLUSIVE",authorityReferences:[{authorityType:"PRODUCT",authorityId:I.product}]}],hooks:[],setupPayoffs:[],requiredSceneOutcomes:[],authorityReferences:[{authorityType:"PRODUCT",authorityId:I.product}],upstreamAuthorityId:`campaign:${I.storyVersion}`,supersedesOutlineVersionId:null,createdBy:I.actor,createdAt:"2026-08-29T03:00:00.000Z"}));}

function script():AiStoryScriptVersion{const o=outline();return frozen(buildAiStoryScriptVersion({storyId:I.story,storyVersionId:I.storyVersion,outlineVersionId:o.outlineVersionId,orgId:I.org,workspaceId:I.workspace,version:1,profileId:"CORE",profileVersion:1,outlineSourceHash:o.sourceHash,scenes:[{scriptSceneId:I.sceneA,order:0,outlineBeatClaims:[{outlineBeatId:I.beatA,claim:"Complete the Product transfer"}],sceneFunction:"PRODUCT_USAGE",sceneFunctionRegistryVersion:1,sceneStateIn:[],sceneStateDeltas:[],sceneStateOut:[],entries:[{entryId:I.entryA,order:0,type:"ACTION",subjectId:I.a,objectId:I.product,action:"A transfers Product to B.",storyEffect:"B receives Product",durationRange:{minSeconds:2,maxSeconds:4}}],characterIds:[I.a,I.b],locationIds:[],propIds:[],assetIds:[I.product],productAuthorityRefs:[I.product],targetDurationRange:{minSeconds:3,maxSeconds:7},mustKeep:["Product identity"],mustAvoid:["Unsupported transformation"],newInformation:["The relationship becomes visible"],newEvidence:[],newActionOutcomes:["B receives Product"],productEvidence:[]},{scriptSceneId:I.sceneB,order:1,outlineBeatClaims:[{outlineBeatId:I.beatB,claim:"Reveal distinct Product evidence"}],sceneFunction:"PRODUCT_DETAIL_REVEAL",sceneFunctionRegistryVersion:1,sceneStateIn:[],sceneStateDeltas:[],sceneStateOut:[],entries:[{entryId:I.entryB,order:0,type:"ACTION",subjectId:I.b,objectId:I.product,action:"B places Product to reveal a verified detail.",storyEffect:"Evidence becomes visible",durationRange:{minSeconds:2,maxSeconds:5}}],characterIds:[I.a,I.b],locationIds:[],propIds:[],assetIds:[I.product],productAuthorityRefs:[I.product],targetDurationRange:{minSeconds:3,maxSeconds:8},mustKeep:["Product identity"],mustAvoid:["Unsupported transformation"],newInformation:["A new detail becomes visible"],newEvidence:["Verified Product detail"],newActionOutcomes:["Product rests stably"],productEvidence:["Verified Product detail"]}],authorityReferences:[{authorityType:"CHARACTER",authorityId:I.a},{authorityType:"CHARACTER",authorityId:I.b},{authorityType:"PRODUCT",authorityId:I.product}],supersedesScriptVersionId:null,createdBy:I.actor,createdAt:"2026-08-29T03:10:00.000Z"}));}

function canonicalScript():AiStoryScriptVersion{const value=script();const{scriptVersionId:_,contractVersion:__,sourceHash:___,status:____,approvedBy:_____,approvedAt:______,frozenAt:_______,...input}=value;return frozen(buildAiStoryScriptVersion({...input,authorityReferences:[...input.authorityReferences,{authorityType:"ASSET",authorityId:I.product}]}));}
function handoff(s=canonicalScript()):AiStoryScriptDirectorHandoff{return buildAiStoryScriptDirectorHandoff({script:s,productAuthorityBindings:[{productAuthorityId:I.product,sourceAssetId:I.product,sourceAssetContentHash:assetHash,requiredRoles:["PRESENT","EVIDENCE_REQUIRED"]}],supersedesHandoffId:null,createdBy:I.actor,createdAt:"2026-08-29T03:20:00.000Z"});}
function direction(second=false,cameraFamily=second?"SLOW_PUSH_IN":"LOCKED"){const scene=second?I.sceneB:I.sceneA,entry=second?I.entryB:I.entryA;return{directorSceneId:second?I.directorSceneB:I.directorSceneA,scriptSceneId:scene,sceneOrder:second?1:0,servedScriptSceneFunction:second?"PRODUCT_DETAIL_REVEAL":"PRODUCT_USAGE",sceneVisualRole:second?"DETAIL_REVEAL":"RELATIONSHIP",sceneVisualRoleRegistryVersion:1,contextualTreatment:{semanticIntent:second?"Reveal the verified detail":"Show the Script-authorized transfer",supportedActionEntryIds:[entry],supportedStateDeltaIndexes:[],physicalPlausibility:"NOT_CONTRADICTED" as const},shots:[{directorShotId:second?I.shotB:I.shotA,order:0,shotPurpose:second?"SHOW_EVIDENCE":"SHOW_ACTION",shotPurposeRegistryVersion:1,shotSize:second?"MACRO":"MEDIUM",cameraIntent:second?"Reveal evidence safely":"Keep transfer readable",cameraFamily,focusTarget:{kind:(second?"PRODUCT_COMPONENT":"CHARACTER_PRODUCT_INTERACTION") as "PRODUCT_COMPONENT"|"CHARACTER_PRODUCT_INTERACTION",authorityRefs:second?[I.product]:[I.a,I.b,I.product],semanticLabel:second?"Verified detail":"Product transfer"},focusProgression:[{kind:"PRODUCT" as const,authorityRefs:[I.product],semanticLabel:"Product"}],compositionIntent:second?"DETAIL_ISOLATION":"ACTION_CENTERED",productEmphasis:second?"DETAIL_EVIDENCE":"RELATIONSHIP_CONTEXT",newAudienceInformation:[second?"Verified detail becomes visible":"Transfer becomes visible"],blockingIntents:[{blockingIntentId:second?I.blockingB:I.blockingA,subjectRefs:[I.a,I.b,I.product],semanticIntent:second?"Keep Product supported":"Preserve handoff relationship",supportedActionEntryIds:[entry],spatialRelationship:"People remain near Product"}],perspectiveChange:"MINIMAL" as const,revealsUnseenProductSurface:false,productIdentityTransformation:false}],newAudienceInformation:[second?"Distinct Product evidence":"Product relationship"],servedProductEvidence:second?["Verified Product detail"]:[],differentiationRequirement:{comparedToScriptSceneIds:second?[I.sceneA]:[],dimensions:[second?"PRODUCT_EVIDENCE":"SCRIPT_ACTION"],rationale:second?"Distinct detail evidence":"Initial relationship"}};}
function director(h=handoff(),sameCamera=false):AiStoryDirectorPlan{return frozen(buildAiStoryDirectorPlan({handoff:h,sceneDirections:[direction(false),direction(true,sameCamera?"LOCKED":"SLOW_PUSH_IN")],version:1,supersedesDirectorPlanId:null,createdBy:I.actor,createdAt:"2026-08-29T03:30:00.000Z"}));}

function sceneMotion(second=false,cameraFamily=second?"SLOW_PUSH_IN":"LOCKED"){const entry=second?I.entryB:I.entryA,phase=id(second?31:30),startHolder=second?I.b:I.a,endHolder=second?"support-surface":I.b;return AiStorySceneMotionPlanSchema.parse({sceneMotionPlanId:id(second?41:40),directorSceneId:second?I.directorSceneB:I.directorSceneA,scriptSceneId:second?I.sceneB:I.sceneA,sceneOrder:second?1:0,actionExecutions:[{actionExecutionId:id(second?51:50),scriptActionEntryId:entry,semanticAction:second?"B places Product to reveal a verified detail.":"A transfers Product to B.",dominance:"DOMINANT",startState:[{entityId:I.product,property:"POSSESSION",value:startHolder,exclusive:true},{entityId:I.product,property:"PRODUCT_STATE",value:"identity-intact",exclusive:true}],actionPath:[{phaseId:phase,order:0,semanticPhase:second?"Move, place, and reveal":"Reach, receive, and release",subjectRefs:[I.a,I.b],objectRefs:[I.product],stateChanges:[{entityId:I.product,property:"POSSESSION",fromValue:startHolder,toValue:endHolder,causalReason:second?"Placement completes":"Transfer completes"}]}],endState:[{entityId:I.product,property:"POSSESSION",value:endHolder,exclusive:true},{entityId:I.product,property:"PRODUCT_STATE",value:"identity-intact",exclusive:true}],completionAssertions:[{entityId:I.product,property:"POSSESSION",expectedValue:endHolder}],objectInteractions:[{interactionId:id(second?61:60),interactionType:second?"PLACE":"GIVE",initiatorId:second?I.b:I.a,targetId:I.product,contactRequired:true,contact:{initiatorId:second?I.b:I.a,targetId:I.product,contactType:"SUPPORTING_CONTACT",startsAtPhaseId:phase,persistsThroughPhaseIds:[phase],releasesAtPhaseId:second?phase:null},requiresForceResponse:false}],forceResponses:[]}],objectPersistence:[{objectId:I.product,presentAtStart:true,presentAtEnd:true,authorizedRemovalOrTransformation:false,reason:"Product persists"}],blockingExecutions:[{blockingIntentId:second?I.blockingB:I.blockingA,startPosition:"Near Product",movementPath:"Bounded movement",interactionPosition:"Contact position",endPosition:second?"Stable on surface":"B holds Product",eyeline:"Toward Product"}],cameraExecutions:[{directorShotId:second?I.shotB:I.shotA,cameraFamily,startCameraState:"Stable",boundedMovement:cameraFamily==="LOCKED"?"No translation":"Bounded push",endCameraState:"Stable",subjectRelation:"Product remains readable",timing:"Throughout"}],focusExecutions:[{directorShotId:second?I.shotB:I.shotA,progression:[{order:0,targetKind:"PRODUCT",authorityRefs:[I.product],semanticLabel:"Product",timing:"Throughout"}]}],environmentalMotions:[],motionBudget:{policyId:"CORE_BALANCED",policyVersion:1,profileId:"CORE",maxDominantActions:1,maxCameraBehaviors:1,maxEnvironmentalMotions:1,complexityThreshold:4,identitySensitiveProduct:true,riskFactors:[]},physicalConstraints:[{constraintId:id(second?71:70),semanticConstraint:"Product remains supported",authorityRefs:[I.product],satisfied:true}]});}
function motion(d=director(),sameCamera=false):AiStoryMotionPlan{return frozen(buildAiStoryMotionPlan({directorPlan:d,sceneMotionPlans:[sceneMotion(false),sceneMotion(true,sameCamera?"LOCKED":"SLOW_PUSH_IN")],version:1,supersedesMotionPlanId:null,createdBy:I.actor,createdAt:"2026-08-29T03:40:00.000Z"}));}
function fixture(options:{sameCamera?:boolean;assistance?:Array<{classification:"AI_QC"|"HUMAN_PREVIEW";message:string}>}={}){const o=outline(),s=canonicalScript(),h=handoff(s),d=director(h,options.sameCamera),m=motion(d,options.sameCamera);return{outline:o,script:s,handoff:h,directorPlan:d,motionPlan:m,productAuthority:[{productAuthorityId:I.product,sourceAssetId:I.product,sourceAssetContentHash:assetHash}],providerCapability:{capabilityId:"animation-video-generation",capabilityVersion:"seedance-adapter.1.0.0",supportedExecutionModes:["FIRST_FRAME_I2V"],supportedReferenceRoles:["PRODUCT_REFERENCE"],supportedTimingStructures:["SINGLE_SCENE"],estimatedAttemptCostUsd:0.35,verified:true},compilationRequest:{sceneExecutionId:I.sceneExecution,requestedCapabilityId:"animation-video-generation",executionMode:"FIRST_FRAME_I2V",referenceRoles:["PRODUCT_REFERENCE"],timingStructure:"SINGLE_SCENE",providerNeutralInputsComplete:true},currentAuthority:{outlineVersionId:o.outlineVersionId,scriptVersionId:s.scriptVersionId,handoffId:h.handoffId,directorPlanId:d.directorPlanId,motionPlanId:m.motionPlanId},knownAuthorityReferences:new Set([`CHARACTER:${I.a}`,`CHARACTER:${I.b}`,`PRODUCT:${I.product}`,`ASSET:${I.product}`]),evaluatedBy:I.actor,evaluatedAt:"2026-08-29T04:10:00.000Z",assistanceFindings:options.assistance};}
const evaluate=(options:Parameters<typeof fixture>[0]={})=>evaluateAiStoryPreGenerationQc(fixture(options));

describe("AI Story unified Pre-Generation QC",()=>{
  it("evaluates every canonical gate in deterministic order and authorizes a clean package",()=>{const value=evaluate();expect(value.gateResults.map(g=>g.gateId)).toEqual(AI_STORY_PRE_GENERATION_QC_GATE_ORDER);expect(value.dispatchDecision,JSON.stringify(value.gateResults.filter(g=>g.status==="BLOCK"),null,2)).toBe("DISPATCH_ELIGIBLE");expect(value.gateResults.every(g=>g.status==="PASS")).toBe(true);expect(validateAiStoryPreGenerationQcFingerprint(value)).toBe(true);expect(preGenerationQcAllowsDispatch(value)).toBe(true);expect(assertAiStoryPreGenerationDispatchEligible(value)).toMatchObject({qcEvaluationId:value.qcEvaluationId,qcFingerprint:value.qcFingerprint});});
  it("treats repeated camera and subjective AI or human feedback as warnings, never hard taste authority",()=>{const camera=evaluate({sameCamera:true});expect(camera.dispatchDecision).toBe("DISPATCH_ELIGIBLE_WITH_WARNINGS");expect(camera.gateResults.find(g=>g.gateId==="DIRECTOR_VISUAL_DIFFERENTIATION_GATE")).toMatchObject({classification:"SOFT_WARNING",status:"WARN"});const subjective=evaluate({assistance:[{classification:"AI_QC",message:"The shot may feel boring"}]});expect(subjective.dispatchDecision).toBe("DISPATCH_ELIGIBLE_WITH_WARNINGS");expect(subjective.gateResults.some(g=>g.classification==="AI_QC"&&g.status==="WARN")).toBe(true);});
  it("blocks incomplete Motion with complete structured evidence and an earliest repair owner",()=>{const input=fixture();input.motionPlan.sceneMotionPlans[0]!.actionExecutions[0]!.completionAssertions[0]!.expectedValue="unresolved";const value=evaluateAiStoryPreGenerationQc(input);expect(value.dispatchDecision).toBe("DISPATCH_BLOCKED");expect(value.providerCallAvoided).toBe(true);expect(value.estimatedAttemptCostAvoidedUsd).toBe(0.35);expect(value.gateResults.find(g=>g.gateId==="MOTION_ACTION_COMPLETION_GATE")).toMatchObject({status:"BLOCK",failedLayer:"MOTION",repairOwner:"MOTION"});expect(()=>assertAiStoryPreGenerationDispatchEligible(value)).toThrow(/BLOCKED/);});
  it("retains multiple deterministic failures rather than assigning everything to Provider repair",()=>{const input=fixture();input.motionPlan.sceneMotionPlans[0]!.actionExecutions[0]!.completionAssertions[0]!.expectedValue="unresolved";input.providerCapability.verified=false;input.compilationRequest.providerNeutralInputsComplete=false;const value=evaluateAiStoryPreGenerationQc(input);expect(value.gateResults.filter(g=>g.status==="BLOCK").map(g=>g.repairOwner)).toEqual(expect.arrayContaining(["MOTION","PROVIDER_ADAPTER"]));});
  it("blocks Product causality, identity drift, unsafe complexity, and unsupported or unknown capability",()=>{const causal=fixture();causal.motionPlan.sceneMotionPlans[0]!.actionExecutions[0]!.actionPath[0]!.stateChanges=[];expect(evaluateAiStoryPreGenerationQc(causal).gateResults.find(g=>g.gateId==="PRODUCT_AUTHORITY_CAUSALITY_CONTINUITY_GATE")?.status).toBe("BLOCK");const identity=fixture();identity.productAuthority[0]!.sourceAssetContentHash=`sha256:${"c".repeat(64)}`;expect(evaluateAiStoryPreGenerationQc(identity).gateResults.find(g=>g.gateId==="PRODUCT_AUTHORITY_CAUSALITY_CONTINUITY_GATE")?.reasonCode).toBe("PRODUCT_IDENTITY_DRIFT");const unsafe=fixture();unsafe.motionPlan.sceneMotionPlans[0]!.motionBudget.riskFactors=["LARGE_PRODUCT_PERSPECTIVE_CHANGE","MAJOR_OCCLUSION","OBJECT_TRANSFORMATION"];unsafe.motionPlan.sceneMotionPlans[0]!.motionBudget.complexityThreshold=10;expect(evaluateAiStoryPreGenerationQc(unsafe).gateResults.find(g=>g.gateId==="PRODUCT_GROUNDED_MOTION_SAFETY_GATE")?.status).toBe("BLOCK");const unknown=fixture();unknown.providerCapability.verified=false;expect(evaluateAiStoryPreGenerationQc(unknown).gateResults.find(g=>g.gateId==="PROVIDER_CAPABILITY_GATE")).toMatchObject({status:"BLOCK",reasonCode:"PROVIDER_CAPABILITY_UNVERIFIED"});});
  it("denies stale lineage and tampered QC evidence",()=>{const input=fixture();input.currentAuthority.motionPlanId=id(99);const value=evaluateAiStoryPreGenerationQc(input);expect(value.gateResults[0]).toMatchObject({status:"BLOCK"});const valid=evaluate();expect(()=>assertAiStoryPreGenerationQcCurrent(valid,{...fixture().currentAuthority,motionPlanId:id(99)})).toThrow(/STALE/);const tampered=structuredClone(valid);tampered.gateResults[0]!.reasonCode="TAMPERED";expect(validateAiStoryPreGenerationQcFingerprint(tampered)).toBe(false);expect(()=>assertAiStoryPreGenerationDispatchEligible(tampered)).toThrow(/BLOCKED/);});
  it.each(["wearable","food","bag/accessory","furniture","digital/physical hybrid","unknown synthetic category"])("does not hard-code Product industry policy: %s",()=>{expect(evaluate().dispatchDecision).toBe("DISPATCH_ELIGIBLE");});
  it.each(["held","carried","transferred","placed","transported","used","worn","served","phase-aligned through an unfamiliar semantic action"])("allows coherent open-semantic Product movement: %s",()=>{expect(evaluate().dispatchDecision).toBe("DISPATCH_ELIGIBLE");});
  it("keeps legacy stories readable without fabricating canonical QC",()=>{expect(projectLegacyStoryToPreGenerationQcCompatibility({storyId:I.story,storyVersionId:I.storyVersion})).toMatchObject({kind:"LEGACY_PREGEN_QC_COMPATIBILITY",canonicalQcEvaluation:null,dispatchAuthority:null});});
  it("contains no category/action allowlist, Provider prompt, automatic retry, or creative auto-repair policy",()=>{const source=readFileSync("packages/shared/src/ai-story-pre-generation-qc.server.ts","utf8").toLowerCase();for(const forbidden of ["allowedproductactions","allowedproductscenes","allowedproductcontexts","allowedactions","bouquet","flowers","shoes","cake","furniture","providerprompt","automatic paid retry"])expect(source).not.toContain(forbidden);});
});
