import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { AI_STORY_CAMERA_FAMILIES, AI_STORY_DIRECTOR_PLAN_CONTRACT_VERSION, AiStoryDirectorPlanSchema, AiStoryDirectorSceneDirectionSchema, assertAiStoryDirectorPlanTransition, resolveDirectorPlanningAuthority, validateAiStoryDirectorPlan, type AiStoryCanonicalScene, type AiStoryDirectorSceneDirection, type AiStoryScriptDirectorHandoff } from "@ceo-agent/shared";
import { buildAiStoryDirectorPlan, computeAiStoryDirectorPlanFingerprint, computeAiStoryDirectorPlanSourceHash } from "@ceo-agent/shared/server";

const id=(n:number)=>`72000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;
const hash=(c:string)=>`sha256:${c.repeat(64)}`;
const I={org:id(1),workspace:id(2),story:id(3),storyVersion:id(4),outline:id(5),script:id(6),handoff:id(7),actor:id(8),product:id(9),character:id(10),sceneA:id(11),sceneB:id(12),beatA:id(13),beatB:id(14),actionA:id(15),actionB:id(16),directorA:id(17),directorB:id(18),shotA:id(19),shotB:id(20),blockingA:id(21),blockingB:id(22),canonicalVersionA:id(23)};

function sourceScene(scriptSceneId:string,sceneOrder:number,sceneFunction:string,beatId:string,actionId:string,evidence:string[]=[]){return {scriptSceneId,sceneOrder,sceneFunction,sceneFunctionRegistryVersion:1,outlineBeatClaims:[{outlineBeatId:beatId,claim:"Serve frozen beat"}],sceneStateIn:[],sceneStateDeltas:[],sceneStateOut:[],actionEntries:[{entryId:actionId,order:0,type:"ACTION" as const,subjectId:I.character,action:"A Script-authorized interaction occurs.",storyEffect:"Story advances",durationRange:{minSeconds:2,maxSeconds:4}}],dialogueEntries:[],voiceOverEntries:[],entryOrder:[actionId],characterIds:[I.character],locationIds:[],propIds:[],assetIds:[I.product],productAuthorityRefs:[I.product],newInformation:[],newEvidence:[],newActionOutcomes:[],productEvidence:evidence,targetDurationRange:{minSeconds:3,maxSeconds:8},mustKeep:["Product identity"],mustAvoid:["Invented action"]};}
function handoff():AiStoryScriptDirectorHandoff{return {handoffId:I.handoff,storyId:I.story,storyVersionId:I.storyVersion,outlineVersionId:I.outline,scriptVersionId:I.script,orgId:I.org,workspaceId:I.workspace,version:1,contractVersion:"ai-story-script-director-handoff.v1",scriptSourceHash:hash("a"),sceneHandoffs:[sourceScene(I.sceneA,0,"PRODUCT_INTRODUCTION",I.beatA,I.actionA),sourceScene(I.sceneB,1,"PRODUCT_DETAIL_REVEAL",I.beatB,I.actionB,["Verified detail"])],productAuthorityBindings:[{productAuthorityId:I.product,sourceAssetId:I.product,sourceAssetContentHash:hash("b"),requiredRoles:["PRESENT","EVIDENCE_REQUIRED"]}],characterWorldRefs:[],sourceHash:hash("c"),handoffFingerprint:hash("d"),supersedesHandoffId:null,createdBy:I.actor,createdAt:"2026-08-29T01:00:00.000Z",frozenAt:"2026-08-29T01:00:00.000Z"};}
function direction(which:"A"|"B",overrides:Partial<AiStoryDirectorSceneDirection>={}):AiStoryDirectorSceneDirection {const second=which==="B";const sceneId=second?I.sceneB:I.sceneA;const actionId=second?I.actionB:I.actionA;return AiStoryDirectorSceneDirectionSchema.parse({directorSceneId:second?I.directorB:I.directorA,scriptSceneId:sceneId,sceneOrder:second?1:0,servedScriptSceneFunction:second?"PRODUCT_DETAIL_REVEAL":"PRODUCT_INTRODUCTION",sceneVisualRole:second?"DETAIL_REVEAL":"HERO_INTRODUCTION",sceneVisualRoleRegistryVersion:1,contextualTreatment:{semanticIntent:second?"Reveal verified evidence":"Introduce the subject",supportedActionEntryIds:[actionId],supportedStateDeltaIndexes:[],physicalPlausibility:"NOT_CONTRADICTED"},shots:[{directorShotId:second?I.shotB:I.shotA,order:0,shotPurpose:second?"SHOW_DETAIL":"REVEAL_SUBJECT",shotPurposeRegistryVersion:1,shotSize:second?"MACRO":"MEDIUM",cameraIntent:second?"Make evidence legible":"Orient the audience",cameraFamily:"SLOW_PUSH_IN",focusTarget:{kind:"PRODUCT",authorityRefs:[I.product],semanticLabel:second?"Verified component":"Whole product"},focusProgression:[{kind:"PRODUCT",authorityRefs:[I.product],semanticLabel:second?"Verified component":"Whole product"}],compositionIntent:second?"DETAIL_ISOLATION":"PRODUCT_DOMINANT",productEmphasis:second?"DETAIL_EVIDENCE":"PRIMARY_HERO",newAudienceInformation:[second?"A verified detail becomes visible":"The overall product becomes visible"],blockingIntents:[{blockingIntentId:second?I.blockingB:I.blockingA,subjectRefs:[I.character,I.product],semanticIntent:"Keep the interaction readable",supportedActionEntryIds:[actionId],spatialRelationship:"Character remains near Product"}],perspectiveChange:"MINIMAL",revealsUnseenProductSurface:false,productIdentityTransformation:false}],newAudienceInformation:[second?"Evidence becomes understandable":"Overall identity becomes understandable"],servedProductEvidence:second?["Verified detail"]:[],differentiationRequirement:{comparedToScriptSceneIds:second?[I.sceneA]:[],dimensions:second?["VISUAL_ROLE","FOCUS","PRODUCT_EVIDENCE"]:["VISUAL_ROLE"],rationale:second?"Detail evidence differs from introduction":"Opening visual authority"},...overrides});}
function plan(directions=[direction("A"),direction("B")]){return buildAiStoryDirectorPlan({handoff:handoff(),sceneDirections:directions,version:1,supersedesDirectorPlanId:null,createdBy:I.actor,createdAt:"2026-08-29T01:01:00.000Z"});}
function issues(value=plan()){return validateAiStoryDirectorPlan(value,handoff(),{expectedSourceHash:computeAiStoryDirectorPlanSourceHash(value),expectedFingerprint:computeAiStoryDirectorPlanFingerprint(value),currentHandoffId:I.handoff});}

describe("AI Director visual authority",()=>{
  it("builds a deterministic versioned provider-neutral plan from the exact frozen handoff",()=>{const value=plan();expect(value.contractVersion).toBe(AI_STORY_DIRECTOR_PLAN_CONTRACT_VERSION);expect(value).toEqual(plan());expect(issues(value).filter(i=>i.severity==="BLOCK")).toEqual([]);expect(JSON.stringify(value).toLowerCase()).not.toMatch(/seedance|providerrequest|actionpath|contactmechanics|forcechain/);});
  it("keeps Script truth outside Director ownership",()=>{const raw={...direction("A"),dialogueEntries:[{line:"rewrite"}]};expect(AiStoryDirectorSceneDirectionSchema.safeParse(raw).success).toBe(false);expect(issues({...plan(),sceneDirections:[direction("A"),direction("B",{servedScriptSceneFunction:"PAYOFF"})]}).some(i=>i.gate==="SCRIPT_TRUTH_BINDING_GATE")).toBe(true);});
  it("binds exact frozen canonical Scene authority when the Scene layer is present",()=>{const binding={sceneId:I.sceneA,sceneVersionId:I.canonicalVersionA,sceneFingerprint:hash("e"),sourceScriptSceneIds:[I.sceneA]};const first=direction("A",{canonicalSceneBinding:binding});const one={...handoff(),sceneHandoffs:[handoff().sceneHandoffs[0]!]};const value=buildAiStoryDirectorPlan({handoff:one,sceneDirections:[first],version:1,supersedesDirectorPlanId:null,createdBy:I.actor,createdAt:"2026-08-29T01:01:00.000Z"});const canonical={sceneId:I.sceneA,sceneVersionId:I.canonicalVersionA,fingerprint:hash("e"),sourceScriptSceneIds:[I.sceneA],status:"FROZEN"} as AiStoryCanonicalScene;expect(validateAiStoryDirectorPlan(value,one,{canonicalScenes:[canonical],requireCanonicalSceneBindings:true}).some(i=>i.gate==="CANONICAL_SCENE_BINDING_GATE")).toBe(false);expect(validateAiStoryDirectorPlan(value,one,{canonicalScenes:[{...canonical,fingerprint:hash("f")}],requireCanonicalSceneBindings:true}).some(i=>i.gate==="CANONICAL_SCENE_BINDING_GATE")).toBe(true);});
  it("denies Director action or focus authority not present in the Script",()=>{const bad=direction("B");bad.contextualTreatment.supportedActionEntryIds=[id(99)];expect(issues(plan([direction("A"),bad])).some(i=>i.gate==="SCRIPT_ACTION_SUPPORT_GATE")).toBe(true);const focus=direction("B");focus.shots[0]!.focusTarget.authorityRefs=[id(98)];expect(issues(plan([direction("A"),focus])).some(i=>i.gate==="FOCUS_REFERENCE_GATE")).toBe(true);});
  it("blocks the R4 repeated hero treatment before Motion",()=>{const repeated=direction("B",{sceneVisualRole:"HERO_INTRODUCTION",contextualTreatment:{semanticIntent:"Introduce the subject",supportedActionEntryIds:[I.actionB],supportedStateDeltaIndexes:[],physicalPlausibility:"NOT_CONTRADICTED"},newAudienceInformation:[],servedProductEvidence:[]});repeated.shots=[{...direction("A").shots[0]!,directorShotId:I.shotB,newAudienceInformation:[]}];const result=issues(plan([direction("A"),repeated]));expect(result.some(i=>i.gate==="DIRECTOR_VISUAL_DUPLICATION_GATE"&&i.severity==="BLOCK")).toBe(true);});
  it("allows the distinct detail treatment and repeated camera family",()=>{expect(direction("A").shots[0]!.cameraFamily).toBe(direction("B").shots[0]!.cameraFamily);expect(issues().some(i=>i.severity==="BLOCK")).toBe(false);});
  it.each(["transfer between people","transport through an environment","lifestyle relationship","wearable use","serving interaction","large-object relationship","unknown synthetic context"])("generalizes through Script-supported open semantics: %s",semanticIntent=>{const value=direction("A",{contextualTreatment:{semanticIntent,supportedActionEntryIds:[I.actionA],supportedStateDeltaIndexes:[],physicalPlausibility:"NOT_CONTRADICTED"}});const one={...handoff(),sceneHandoffs:[handoff().sceneHandoffs[0]!],productAuthorityBindings:handoff().productAuthorityBindings};const built=buildAiStoryDirectorPlan({handoff:one,sceneDirections:[value],version:1,supersedesDirectorPlanId:null,createdBy:I.actor,createdAt:"2026-08-29T01:01:00.000Z"});expect(validateAiStoryDirectorPlan(built,one,{expectedSourceHash:computeAiStoryDirectorPlanSourceHash(built),expectedFingerprint:computeAiStoryDirectorPlanFingerprint(built),currentHandoffId:one.handoffId}).filter(i=>i.severity==="BLOCK")).toEqual([]);});
  it("does not require a Product category and supports namespaced registry extensions",()=>{const value=direction("A",{sceneVisualRole:"EXT:studio.example:NOVEL_TREATMENT"});expect(value).not.toHaveProperty("productCategory");expect(value.sceneVisualRole).toContain("EXT:");});
  it("preserves Product camera safety without requiring a static Product",()=>{const unsafe=direction("B");unsafe.shots[0]!.perspectiveChange="LARGE";expect(issues(plan([direction("A"),unsafe])).some(i=>i.gate==="PRODUCT_CAMERA_SAFETY_GATE")).toBe(true);expect(AI_STORY_CAMERA_FAMILIES).toContain("TRACKING");});
  it("rejects low-level Motion fields at the Director schema boundary",()=>{const raw={...direction("A"),shots:[{...direction("A").shots[0],actionPath:"exact path",contactForce:4,terminalPhysicalState:"final pose"}]};expect(AiStoryDirectorSceneDirectionSchema.safeParse(raw).success).toBe(false);});
  it("enforces lifecycle and freeze transitions",()=>{expect(()=>assertAiStoryDirectorPlanTransition("DRAFT","APPROVED")).toThrow(/DENIED/);expect(()=>assertAiStoryDirectorPlanTransition("FROZEN","DRAFT")).toThrow(/DENIED/);expect(()=>assertAiStoryDirectorPlanTransition("DRAFT","VALIDATED")).not.toThrow();});
  it("makes canonical Director authority outrank legacy planning",()=>{expect(resolveDirectorPlanningAuthority({canonicalDirectorPlan:plan(),legacyPlanning:{directorThinking:"legacy"}}).kind).toBe("CANONICAL_DIRECTOR_PLAN");expect(resolveDirectorPlanningAuthority({legacyPlanning:{scenePlan:[]}}).kind).toBe("LEGACY_DIRECTOR_PLANNING_COMPATIBILITY");});
  it("contains no category-specific production policy",()=>{const source=readFileSync("packages/shared/src/ai-story-director-plan.ts","utf8").toLowerCase();for(const word of ["bouquet","flowers","shoes","cake","bag","furniture","allowedproductactions","allowedproductscenes","allowedproductcontexts"])expect(source).not.toContain(word);});
});
