import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Sql } from "postgres";
import {
  AiStoryOutlineAuthorityService,
  AiStoryScriptAuthorityService,
  AiStoryScriptDirectorHandoffAuthorityService,
  AiStoryDirectorPlanAuthorityService,
  closeDb,
} from "@ceo-agent/db";
import { buildAiStoryOutlineVersion, buildAiStoryScriptVersion } from "@ceo-agent/shared/server";
import { RUN_DB_INTEGRATION, cleanupRlsFixture, createIntegrationSql, getIntegrationDbUrl, seedRlsFixture, withAuthenticatedUser, type RlsTestFixture } from "./helpers/db-integration";

const describeIntegration = RUN_DB_INTEGRATION && getIntegrationDbUrl() ? describe : describe.skip;
const id=(n:number)=>`62000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;
const I={story:id(1),storyVersion:id(2),unit:id(3),beat:id(4),scene:id(5),entry:id(6),character:id(7),product:id(8)};

describeIntegration("AI Story immutable Script Director handoff persistence",()=>{
  let sql:Sql;let fixture:RlsTestFixture;let handoffA:string;let handoffB:string;let scriptA:string;let scriptB:string;let directorPlanId:string;
  beforeAll(async()=>{
    sql=createIntegrationSql();fixture=await seedRlsFixture(sql);
    await sql.unsafe(`DO $$ BEGIN CREATE ROLE authenticated NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$; CREATE SCHEMA IF NOT EXISTS auth; CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;`);
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-outline-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-script-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-script-director-handoff-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-director-plan-v1.sql"),"utf8"));
    await sql.unsafe("GRANT USAGE ON SCHEMA public TO authenticated; GRANT SELECT ON workspace_members,ai_story_script_versions,ai_story_script_director_handoffs,ai_story_director_plan_versions TO authenticated; GRANT INSERT,UPDATE ON ai_story_script_director_handoffs,ai_story_director_plan_versions TO authenticated");
    await sql`insert into ai_stories(id,org_id,workspace_id,campaign_id,title,original_idea,status) values(${I.story}::uuid,${fixture.orgId}::uuid,${fixture.workspaceAId}::uuid,${fixture.campaignAId}::uuid,'Handoff test','Idea','draft')`;
    await sql`insert into ai_story_versions(id,story_id,version_number,structured_content) values(${I.storyVersion}::uuid,${I.story}::uuid,1,${sql.json({title:"Legacy",summary:"",objective:"",targetAudience:"",tone:"",estimatedDuration:"",story:{opening:"",development:"",ending:""},keyMessages:[],cta:"",assetReferences:[],warnings:[]})})`;
    await sql`insert into assets(id,org_id,workspace_id,campaign_id,type,storage_path,status,source,content_hash) values(${I.product}::uuid,${fixture.orgId}::uuid,${fixture.workspaceAId}::uuid,${fixture.campaignAId}::uuid,'product','private/handoff-product.png','ready','campaign_upload',${`sha256:${"b".repeat(64)}`})`;
    const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};
    const outline=buildAiStoryOutlineVersion({storyId:I.story,storyVersionId:I.storyVersion,orgId:fixture.orgId,workspaceId:fixture.workspaceAId,version:1,profile:{profileId:"CORE",profileVersion:1},premise:"A decision needs proof",coreClaim:"Exact product evidence resolves doubt",storyUnits:[{storyUnitId:I.unit,order:0,purpose:"Complete story",summary:"Proof",requiredBeatIds:[I.beat]}],beats:[{id:I.beat,storyUnitId:I.unit,order:0,classification:"MAJOR",name:"Proof",purpose:"Reveal evidence",summary:"Evidence changes the decision",required:true,ownershipPolicy:"EXCLUSIVE",authorityReferences:[{authorityType:"PRODUCT",authorityId:I.product}]}],hooks:[],setupPayoffs:[],requiredSceneOutcomes:[],authorityReferences:[{authorityType:"PRODUCT",authorityId:I.product}],upstreamAuthorityId:`${fixture.campaignAId}:${I.storyVersion}`,supersedesOutlineVersionId:null,createdBy:fixture.userAId,createdAt:"2026-08-28T02:00:00.000Z"});
    const outlines=new AiStoryOutlineAuthorityService();await outlines.propose(scope,outline);await outlines.validate(scope,outline.outlineVersionId);await outlines.approve(scope,outline.outlineVersionId);const frozenOutline=await outlines.freeze(scope,outline.outlineVersionId);
    const makeScript=(version:number,supersedesScriptVersionId:string|null,action:string,createdAt:string)=>buildAiStoryScriptVersion({storyId:I.story,storyVersionId:I.storyVersion,outlineVersionId:outline.outlineVersionId,orgId:fixture.orgId,workspaceId:fixture.workspaceAId,version,profileId:"CORE",profileVersion:1,outlineSourceHash:frozenOutline.sourceHash,scenes:[{scriptSceneId:I.scene,order:0,outlineBeatClaims:[{outlineBeatId:I.beat,claim:"Reveal the verified product detail"}],sceneFunction:"PRODUCT_DETAIL_REVEAL",sceneFunctionRegistryVersion:1,sceneStateIn:[],sceneStateDeltas:[],sceneStateOut:[],entries:[{entryId:I.entry,order:0,type:"ACTION",subjectId:I.product,action,storyEffect:"Evidence resolves doubt",durationRange:{minSeconds:2,maxSeconds:5}}],characterIds:[I.character],locationIds:[],propIds:[],assetIds:[],productAuthorityRefs:[I.product],targetDurationRange:{minSeconds:3,maxSeconds:9},mustKeep:["Exact product"],mustAvoid:["Unsupported claim"],newInformation:["Detail visible"],newEvidence:["Verified product detail"],newActionOutcomes:["Decision changes"],productEvidence:["Verified product detail"]}],authorityReferences:[{authorityType:"CHARACTER",authorityId:I.character},{authorityType:"PRODUCT",authorityId:I.product}],supersedesScriptVersionId,createdBy:fixture.userAId,createdAt});
    const scripts=new AiStoryScriptAuthorityService();const handoffs=new AiStoryScriptDirectorHandoffAuthorityService();
    const first=makeScript(1,null,"The product detail is inspected.","2026-08-28T02:01:00.000Z");scriptA=first.scriptVersionId;await scripts.propose(scope,first);await scripts.validate(scope,scriptA);await scripts.approve(scope,scriptA);await scripts.freeze(scope,scriptA);handoffA=(await handoffs.createFromFrozenScript(scope,scriptA,"2026-08-28T02:02:00.000Z")).handoff.handoffId;
    const second=makeScript(2,scriptA,"The stronger verified detail is inspected.","2026-08-28T02:03:00.000Z");scriptB=second.scriptVersionId;await scripts.propose(scope,second);expect((await handoffs.validate(scope,handoffA)).some(issue=>issue.gate==="STALE_HANDOFF_GATE")).toBe(true);await scripts.validate(scope,scriptB);await scripts.approve(scope,scriptB);await scripts.freeze(scope,scriptB);handoffB=(await handoffs.createFromFrozenScript(scope,scriptB,"2026-08-28T02:04:00.000Z")).handoff.handoffId;
    const director=new AiStoryDirectorPlanAuthorityService();const proposed=await director.propose(scope,{handoffId:handoffB,createdAt:"2026-08-28T02:05:00.000Z",sceneDirections:[{directorSceneId:id(20),scriptSceneId:I.scene,sceneOrder:0,servedScriptSceneFunction:"PRODUCT_DETAIL_REVEAL",sceneVisualRole:"DETAIL_REVEAL",sceneVisualRoleRegistryVersion:1,contextualTreatment:{semanticIntent:"Make the Script-authorized evidence visually legible",supportedActionEntryIds:[I.entry],supportedStateDeltaIndexes:[],physicalPlausibility:"NOT_CONTRADICTED"},shots:[{directorShotId:id(21),order:0,shotPurpose:"SHOW_EVIDENCE",shotPurposeRegistryVersion:1,shotSize:"MACRO",cameraIntent:"Preserve identity while making the evidence readable",cameraFamily:"LOCKED",focusTarget:{kind:"PRODUCT_COMPONENT",authorityRefs:[I.product],semanticLabel:"Verified product detail"},focusProgression:[{kind:"PRODUCT",authorityRefs:[I.product],semanticLabel:"Product"},{kind:"PRODUCT_COMPONENT",authorityRefs:[I.product],semanticLabel:"Verified detail"}],compositionIntent:"DETAIL_ISOLATION",productEmphasis:"DETAIL_EVIDENCE",newAudienceInformation:["The verified detail is visible"],blockingIntents:[],perspectiveChange:"MINIMAL",revealsUnseenProductSurface:false,productIdentityTransformation:false}],newAudienceInformation:["The claim is supported visually"],servedProductEvidence:["Verified product detail"],differentiationRequirement:{comparedToScriptSceneIds:[],dimensions:["PRODUCT_EVIDENCE","FOCUS"],rationale:"Single-scene evidence treatment"}}]});directorPlanId=proposed.directorPlanId;await director.transition(scope,directorPlanId,"VALIDATED");await director.transition(scope,directorPlanId,"APPROVED");await director.transition(scope,directorPlanId,"FROZEN");
  },30000);
  afterAll(async()=>{await closeDb();if(!sql)return;await sql`delete from ai_story_director_plan_versions where story_id=${I.story}::uuid`;await sql`delete from ai_story_script_director_handoffs where story_id=${I.story}::uuid`;await sql`delete from ai_story_script_versions where story_id=${I.story}::uuid`;await sql`delete from ai_story_outline_versions where story_id=${I.story}::uuid`;await sql`delete from assets where id=${I.product}::uuid`;await sql`delete from ai_story_versions where story_id=${I.story}::uuid`;await sql`delete from ai_stories where id=${I.story}::uuid`;await cleanupRlsFixture(sql,fixture);await sql.end();},30000);
  it("stores exact lineage and supersedes stale handoffs without rewriting history",async()=>{const rows=await sql<{handoff_id:string;script_version_id:string;authority_status:string;version:number}[]>`select handoff_id,script_version_id,authority_status,version from ai_story_script_director_handoffs where story_id=${I.story}::uuid order by version`;expect(rows).toEqual([{handoff_id:handoffA,script_version_id:scriptA,authority_status:"SUPERSEDED",version:1},{handoff_id:handoffB,script_version_id:scriptB,authority_status:"CURRENT",version:2}]);});
  it("binds exact product source content and validates current authority",async()=>{const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};const service=new AiStoryScriptDirectorHandoffAuthorityService();const record=await service.read(scope,handoffB);expect(record.handoff.productAuthorityBindings).toEqual([{productAuthorityId:I.product,sourceAssetId:I.product,sourceAssetContentHash:`sha256:${"b".repeat(64)}`,requiredRoles:["PRESENT","EVIDENCE_REQUIRED"]}]);expect(await service.validate(scope,handoffB)).toEqual([]);});
  it("enables RLS and denies cross-workspace reads",async()=>{const [rls]=await sql<{enabled:boolean}[]>`select relrowsecurity enabled from pg_class where oid='ai_story_script_director_handoffs'::regclass`;expect(rls?.enabled).toBe(true);const own=await withAuthenticatedUser(sql,fixture.userAId,tx=>tx<{handoff_id:string}[]>`select handoff_id from ai_story_script_director_handoffs order by version`);expect(own.map(row=>row.handoff_id)).toEqual([handoffA,handoffB]);const cross=await withAuthenticatedUser(sql,fixture.userBId,tx=>tx<{handoff_id:string}[]>`select handoff_id from ai_story_script_director_handoffs`);expect(cross).toEqual([]);});
  it("rejects all frozen handoff content mutation",async()=>{await expect(withAuthenticatedUser(sql,fixture.userAId,tx=>tx`update ai_story_script_director_handoffs set handoff=jsonb_set(handoff,'{sceneHandoffs,0,mustKeep}','[]') where handoff_id=${handoffB}::uuid`)).rejects.toThrow(/immutable/i);});
  it("rejects cross-workspace service authority",async()=>{const service=new AiStoryScriptDirectorHandoffAuthorityService();await expect(service.read({orgId:fixture.orgId,workspaceId:fixture.workspaceBId,campaignId:fixture.campaignBId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userBId},handoffB)).rejects.toThrow(/scope/i);});
  it("persists, validates, approves, and freezes Director authority under tenant RLS",async()=>{const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};const service=new AiStoryDirectorPlanAuthorityService();const value=await service.read(scope,directorPlanId);expect(value.status).toBe("FROZEN");expect((await service.validate(scope,directorPlanId)).filter(issue=>issue.severity==="BLOCK")).toEqual([]);const own=await withAuthenticatedUser(sql,fixture.userAId,tx=>tx<{director_plan_id:string}[]>`select director_plan_id from ai_story_director_plan_versions`);expect(own).toEqual([{director_plan_id:directorPlanId}]);const cross=await withAuthenticatedUser(sql,fixture.userBId,tx=>tx`select director_plan_id from ai_story_director_plan_versions`);expect(cross).toEqual([]);});
  it("makes frozen Director content immutable",async()=>{await expect(withAuthenticatedUser(sql,fixture.userAId,tx=>tx`update ai_story_director_plan_versions set director_plan=jsonb_set(director_plan,'{sceneDirections,0,sceneVisualRole}','\"PACKSHOT\"') where director_plan_id=${directorPlanId}::uuid`)).rejects.toThrow(/immutable/i);});
});
