import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Sql } from "postgres";
import { AiStoryCharacterAuthorityService, AiStoryOutlineAuthorityService, AiStoryScriptAuthorityService, closeDb } from "@ceo-agent/db";
import { buildAiStoryOutlineVersion, buildAiStoryScriptVersion } from "@ceo-agent/shared/server";
import { RUN_DB_INTEGRATION, cleanupRlsFixture, createIntegrationSql, getIntegrationDbUrl, seedRlsFixture, withAuthenticatedUser, type RlsTestFixture } from "./helpers/db-integration";

const describeIntegration = RUN_DB_INTEGRATION && getIntegrationDbUrl() ? describe : describe.skip;
const id=(n:number)=>`50000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;
const I={story:id(1),storyVersion:id(2),unit:id(3),beat:id(4),scene:id(5),entry:id(6),character:id(7),crossScript:id(8)};

describeIntegration("AI Story Script additive persistence and authority",()=>{
  let sql:Sql;let fixture:RlsTestFixture;let outlineId:string;let scriptA:string;let scriptB:string;
  beforeAll(async()=>{
    sql=createIntegrationSql();fixture=await seedRlsFixture(sql);
    await sql.unsafe(`DO $$ BEGIN CREATE ROLE authenticated NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$; CREATE SCHEMA IF NOT EXISTS auth; CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;`);
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-outline-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-script-v1.sql"),"utf8"));
    await sql.unsafe("GRANT USAGE ON SCHEMA public TO authenticated; GRANT SELECT ON workspace_members,ai_story_outline_versions,ai_story_script_versions TO authenticated; GRANT INSERT,UPDATE ON ai_story_script_versions TO authenticated");
    await sql`insert into ai_stories(id,org_id,workspace_id,campaign_id,title,original_idea,status) values(${I.story}::uuid,${fixture.orgId}::uuid,${fixture.workspaceAId}::uuid,${fixture.campaignAId}::uuid,'Script test','Idea','draft')`;
    await sql`insert into ai_story_versions(id,story_id,version_number,structured_content) values(${I.storyVersion}::uuid,${I.story}::uuid,1,${sql.json({title:"Legacy",summary:"",objective:"",targetAudience:"",tone:"",estimatedDuration:"",story:{opening:"",development:"",ending:""},keyMessages:[],cta:"",assetReferences:[],warnings:[]})})`;
    const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};
    const character=await new AiStoryCharacterAuthorityService().add({orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,actorUserId:fixture.userAId},{name:"Ada",identity:"Campaign founder",appearance:"Cobalt jacket",personality:"Observant and direct",emotionalArc:"Doubt to confidence",relationships:[],visualAssetIds:[]},I.character,"2026-08-27T23:59:00.000Z");
    const characterRef={authorityType:"CHARACTER" as const,authorityId:I.character,authorityVersionId:character.characterVersionId,authorityFingerprint:character.fingerprint};
    const outline=buildAiStoryOutlineVersion({storyId:I.story,storyVersionId:I.storyVersion,orgId:fixture.orgId,workspaceId:fixture.workspaceAId,version:1,profile:{profileId:"CORE",profileVersion:1},premise:"A decision needs evidence",coreClaim:"Visible evidence changes the decision",storyUnits:[{storyUnitId:I.unit,order:0,purpose:"Complete story",summary:"Evidence",requiredBeatIds:[I.beat]}],beats:[{id:I.beat,storyUnitId:I.unit,order:0,classification:"MAJOR",name:"Evidence",purpose:"Prove the claim",summary:"The character sees proof",required:true,ownershipPolicy:"EXCLUSIVE",authorityReferences:[characterRef]}],hooks:[],setupPayoffs:[],requiredSceneOutcomes:[],authorityReferences:[characterRef],upstreamAuthorityId:`${fixture.campaignAId}:${I.storyVersion}`,supersedesOutlineVersionId:null,createdBy:fixture.userAId,createdAt:"2026-08-28T00:00:00.000Z"});
    outlineId=outline.outlineVersionId;const outlines=new AiStoryOutlineAuthorityService();await outlines.propose(scope,outline);await outlines.validate(scope,outlineId);await outlines.approve(scope,outlineId);const frozen=await outlines.freeze(scope,outlineId);
    const create=(version:number,supersedesScriptVersionId:string|null,createdAt:string,action:string)=>buildAiStoryScriptVersion({storyId:I.story,storyVersionId:I.storyVersion,outlineVersionId:outlineId,orgId:fixture.orgId,workspaceId:fixture.workspaceAId,version,profileId:"CORE",profileVersion:1,outlineSourceHash:frozen.sourceHash,scenes:[{scriptSceneId:I.scene,order:0,outlineBeatClaims:[{outlineBeatId:I.beat,claim:"Deliver evidence"}],sceneFunction:"DEMONSTRATE",sceneFunctionRegistryVersion:1,sceneStateIn:[],sceneStateDeltas:[],sceneStateOut:[],entries:[{entryId:I.entry,order:0,type:"ACTION",subjectId:I.character,action,storyEffect:"Evidence changes the decision",durationRange:{minSeconds:2,maxSeconds:4}}],characterIds:[I.character],locationIds:[],propIds:[],assetIds:[],productAuthorityRefs:[],targetDurationRange:{minSeconds:2,maxSeconds:8},mustKeep:["Evidence"],mustAvoid:["Camera direction"],newInformation:["Evidence is visible"],newEvidence:["Observable proof"],newActionOutcomes:["Decision changes"],productEvidence:[]}],authorityReferences:[characterRef],supersedesScriptVersionId,createdBy:fixture.userAId,createdAt});
    const service=new AiStoryScriptAuthorityService();const first=create(1,null,"2026-08-28T00:01:00.000Z","The character verifies the evidence.");scriptA=first.scriptVersionId;await service.propose(scope,first);await service.validate(scope,scriptA);await service.approve(scope,scriptA);await service.freeze(scope,scriptA);
    const second=create(2,scriptA,"2026-08-28T00:02:00.000Z","The character verifies the stronger evidence.");scriptB=second.scriptVersionId;await service.propose(scope,second);await service.validate(scope,scriptB);await service.approve(scope,scriptB);await service.freeze(scope,scriptB);
    await sql`insert into ai_story_script_versions(script_version_id,org_id,workspace_id,campaign_id,story_id,story_version_id,outline_version_id,version,contract_version,profile_id,profile_version,outline_source_hash,source_hash,status,script,created_by,created_at) values(${I.crossScript}::uuid,${fixture.orgId}::uuid,${fixture.workspaceBId}::uuid,${fixture.campaignAId}::uuid,${I.story}::uuid,${I.storyVersion}::uuid,${outlineId}::uuid,3,'ai-story-script.v1','CORE',1,${frozen.sourceHash},${`sha256:${"c".repeat(64)}`},'DRAFT',${sql.json({status:"DRAFT"})},${fixture.userAId}::uuid,now())`;
  },30000);
  afterAll(async()=>{await closeDb();if(!sql)return;await sql`delete from ai_story_script_versions where story_id=${I.story}::uuid`;await sql`delete from ai_story_outline_versions where story_id=${I.story}::uuid`;await sql`delete from ai_story_character_versions where character_id=${I.character}::uuid`;await sql`delete from ai_story_characters where character_id=${I.character}::uuid`;await sql`delete from ai_story_versions where story_id=${I.story}::uuid`;await sql`delete from ai_stories where id=${I.story}::uuid`;await cleanupRlsFixture(sql,fixture);await sql.end();},30000);
  it("enables RLS and denies cross-workspace access",async()=>{const [rls]=await sql<{enabled:boolean}[]>`select relrowsecurity enabled from pg_class where oid='ai_story_script_versions'::regclass`;expect(rls?.enabled).toBe(true);const rows=await withAuthenticatedUser(sql,fixture.userAId,tx=>tx<{script_version_id:string}[]>`select script_version_id from ai_story_script_versions`);expect(rows.map(r=>r.script_version_id).sort()).toEqual([scriptA,scriptB].sort());});
  it("enforces frozen immutability",async()=>{await expect(withAuthenticatedUser(sql,fixture.userAId,tx=>tx`update ai_story_script_versions set script=jsonb_set(script,'{scenes,0,mustKeep}','["Changed"]') where script_version_id=${scriptB}::uuid`)).rejects.toThrow(/immutable/i);});
  it("preserves exact version and supersession lineage",async()=>{const rows=await sql<{script_version_id:string;status:string;version:number}[]>`select script_version_id,status,version from ai_story_script_versions where workspace_id=${fixture.workspaceAId}::uuid order by version`;expect(rows).toEqual([{script_version_id:scriptA,status:"SUPERSEDED",version:1},{script_version_id:scriptB,status:"FROZEN",version:2}]);});
});
