import { describe, expect, it } from "vitest";
import {
  AI_STORY_PRE_GENERATION_QC_GATE_ORDER,
  AI_STORY_SEEDANCE_CAPABILITY_CONTRACT_VERSION,
  AI_STORY_SEEDANCE_MAPPING_VERSION,
  AI_STORY_SCENE_EXECUTION_PACKAGE_CONTRACT_VERSION,
  AI_STORY_SEEDANCE_TRANSLATION_MATRIX,
  createExecutionEnvelope,
} from "@ceo-agent/shared";
import { computeAiStoryPreGenerationQcFingerprint, computeAiStorySceneFingerprint, computeAiStorySceneSourceHash } from "@ceo-agent/shared/server";
import {
  compileSceneExecutionPackageForSeedance,
  seedanceSceneExecutionPackageFingerprint,
} from "../packages/agents/src/ai-story/seedance-director-adapter";
import {
  AiStoryCompiledRequestWorkerRuntime,
  AiStoryProviderRuntimeError,
  InMemoryAiStoryProviderRuntimeRepository,
  compileImmutableSeedanceRequest,
  createAiStoryProviderAttempt,
} from "../packages/agents/src/ai-story/provider-runtime-dispatch-integration";
import { mapCanonicalEnvelopeToSeedanceRequest } from "../packages/agents/src/ai-story/seedance-request-mapping";
import { createMemorySeedancePayloadResolver } from "../packages/agents/src/ai-story/seedance-canonical-adapter";

const id = (n: number) => `81000000-0000-4000-8000-${n.toString().padStart(12, "0")}`;
const hash = (character: string) => {
  const hex = ["a", "b", "c", "d", "e", "f"][character.charCodeAt(0) % 6]!;
  return `sha256:${hex.repeat(64)}`;
};
const I = {
  org:id(1), workspace:id(2), campaign:id(3), story:id(4), storyVersion:id(5), outline:id(6), script:id(7), handoff:id(8), director:id(9), motion:id(10), qc:id(11), sceneExecution:id(12), scene:id(13), sceneVersion:id(14), scriptScene:id(15), entry:id(16), actor:id(17), character:id(18), characterVersion:id(19), product:id(20), productAsset:id(21), directorScene:id(22), shot:id(23), blocking:id(24), motionScene:id(25), actionExecution:id(26), phase:id(27), interaction:id(28), constraint:id(29), reference:id(30), package:id(31), environment:id(32), evaluator:id(33), pipeline:id(34), correlation:id(35), envelope:id(36), execution:id(37),
};

function packageFixture(options: { mode?: "TEXT_TO_VIDEO"|"FIRST_FRAME_IMAGE_TO_VIDEO"; productRequirement?: "NONE"|"PREFERRED"|"REQUIRED"; withReference?: boolean; qcDecision?: "DISPATCH_ELIGIBLE"|"DISPATCH_ELIGIBLE_WITH_WARNINGS"|"DISPATCH_BLOCKED"; camera?: string; cameraRequired?: "REQUIRED"|"OPTIONAL" } = {}) {
  const mode = options.mode ?? "FIRST_FRAME_IMAGE_TO_VIDEO";
  const productRequirement = options.productRequirement ?? "REQUIRED";
  const sceneBinding = { sceneId:I.scene, sceneVersionId:I.sceneVersion, sceneFingerprint:hash("s"), sourceScriptSceneIds:[I.scriptScene] };
  const artifactIds = { storyId:I.story, storyVersionId:I.storyVersion, outlineVersionId:I.outline, scriptVersionId:I.script, handoffId:I.handoff, directorPlanId:I.director, motionPlanId:I.motion, sceneExecutionId:I.sceneExecution, sceneVersionIds:[I.sceneVersion] };
  const scene = {
    sceneId:I.scene, sceneVersionId:I.sceneVersion, orgId:I.org, workspaceId:I.workspace, campaignId:I.campaign, storyId:I.story, storyVersionId:I.storyVersion, scriptVersionId:I.script,
    version:1, contractVersion:"ai-story-scene.v1", order:0, sourceScriptSceneIds:[I.scriptScene], sourceScriptEntryIds:[I.entry], sceneFunction:"PRODUCT_USAGE", sceneRole:"CONSEQUENTIAL", importance:"MAJOR",
    locationBinding:{scope:"EPHEMERAL_ENVIRONMENT",id:I.environment,storyId:I.story,sceneId:I.scene,displayName:"Unclassified environment",environmentDescription:"A plausible open-semantic setting",visualIdentityRequirement:"NONE"},
    locationState:{timeOfDay:"day",weather:"calm",temporaryFacts:["A clear interaction area"]},
    castBindings:[{scope:"CAMPAIGN_CHARACTER",id:I.character,campaignId:I.campaign,authorityVersionId:I.characterVersion,authorityFingerprint:hash("c"),visualIdentityRequirement:"NONE"}],
    productBindings:[{productAuthorityId:I.product,sourceAssetId:I.productAsset,sourceAssetContentHash:hash("p")}],
    entryState:[{dimension:"POSSESSION",subjectId:I.product,value:"held by the Character"}],
    events:[{entryId:I.entry,order:0,durationRange:{minSeconds:2,maxSeconds:5},type:"ACTION",subjectId:I.character,objectId:I.product,action:"The Character phase-aligns the unknown Product with the display surface.",storyEffect:"Usage evidence becomes visible"}],
    exitState:[{dimension:"PRODUCT_STATE",subjectId:I.product,value:"phase-aligned and visibly intact"}], continuityFacts:["Character and Product identities persist"], timeRelation:"UNSPECIFIED", discontinuity:null,
    mustKeep:["Preserve the authorized action outcome"],mustAvoid:["No identity substitution"],lineageOperation:"CREATE",parentSceneVersionIds:[],sourceHash:hash("h"),fingerprint:hash("s"),status:"FROZEN",createdBy:I.actor,createdAt:"2026-08-29T10:00:00.000Z",approvedBy:I.actor,approvedAt:"2026-08-29T10:01:00.000Z",frozenAt:"2026-08-29T10:02:00.000Z",
  };
  scene.sourceHash=computeAiStorySceneSourceHash(scene as any);
  scene.fingerprint=computeAiStorySceneFingerprint(scene as any);
  sceneBinding.sceneFingerprint=scene.fingerprint;
  const directorDirection = {
    directorSceneId:I.directorScene,scriptSceneId:I.scriptScene,canonicalSceneBinding:sceneBinding,sceneOrder:0,servedScriptSceneFunction:"PRODUCT_USAGE",sceneVisualRole:"USAGE_DEMONSTRATION",sceneVisualRoleRegistryVersion:1,
    contextualTreatment:{semanticIntent:"Make the unfamiliar authorized action legible",supportedActionEntryIds:[I.entry],supportedStateDeltaIndexes:[],physicalPlausibility:"NOT_CONTRADICTED"},
    shots:[{directorShotId:I.shot,order:0,shotPurpose:"SHOW_ACTION",shotPurposeRegistryVersion:1,shotSize:"MEDIUM_CLOSE",cameraIntent:"Keep the causal interaction readable",cameraFamily:options.camera??"LOCKED",focusTarget:{kind:"CHARACTER_PRODUCT_INTERACTION",authorityRefs:[I.character,I.product],semanticLabel:"Character and Product interaction"},focusProgression:[{kind:"CHARACTER",authorityRefs:[I.character],semanticLabel:"Character"},{kind:"PRODUCT",authorityRefs:[I.product],semanticLabel:"Product result"}],compositionIntent:"ACTION_CENTERED",productEmphasis:"USAGE_CONTEXT",newAudienceInformation:["The unfamiliar usage becomes understandable"],blockingIntents:[{blockingIntentId:I.blocking,subjectRefs:[I.character,I.product],semanticIntent:"Keep Character and Product relation readable",supportedActionEntryIds:[I.entry],spatialRelationship:"Character remains beside Product"}],perspectiveChange:"MINIMAL",revealsUnseenProductSurface:false,productIdentityTransformation:false}],
    newAudienceInformation:["The usage outcome becomes visible"],servedProductEvidence:["The Product remains intact after the action"],differentiationRequirement:{comparedToScriptSceneIds:[],dimensions:["SCRIPT_ACTION"],rationale:"New authorized action evidence"},
  };
  const motionScenePlan = {
    sceneMotionPlanId:I.motionScene,directorSceneId:I.directorScene,scriptSceneId:I.scriptScene,sceneOrder:0,canonicalSceneBinding:sceneBinding,
    actionExecutions:[{actionExecutionId:I.actionExecution,scriptActionEntryId:I.entry,semanticAction:"Phase-align the Product with the display surface",dominance:"DOMINANT",startState:[{entityId:I.product,property:"POSSESSION",value:"held by the Character",exclusive:true}],actionPath:[{phaseId:I.phase,order:0,semanticPhase:"Approach, align, and settle",subjectRefs:[I.character],objectRefs:[I.product],stateChanges:[{entityId:I.product,property:"PRODUCT_STATE",fromValue:null,toValue:"phase-aligned",causalReason:"The authorized action completes"}]}],endState:[{entityId:I.product,property:"PRODUCT_STATE",value:"phase-aligned and visibly intact",exclusive:true}],completionAssertions:[{entityId:I.product,property:"PRODUCT_STATE",expectedValue:"phase-aligned and visibly intact"}],objectInteractions:[{interactionId:I.interaction,interactionType:"EXT:test:PHASE_ALIGN",initiatorId:I.character,targetId:I.product,contactRequired:true,contact:{initiatorId:I.character,targetId:I.product,contactType:"EXT:test:GUIDED_CONTACT",startsAtPhaseId:I.phase,persistsThroughPhaseIds:[I.phase],releasesAtPhaseId:I.phase},requiresForceResponse:false}],forceResponses:[]}],
    objectPersistence:[{objectId:I.product,presentAtStart:true,presentAtEnd:true,authorizedRemovalOrTransformation:false,reason:"Product persists"}],blockingExecutions:[{blockingIntentId:I.blocking,startPosition:"Character beside Product",movementPath:"Bounded approach",interactionPosition:"Hands near the supported Product",endPosition:"Product settled on surface",eyeline:"Toward Product"}],cameraExecutions:[{directorShotId:I.shot,cameraFamily:options.camera??"LOCKED",startCameraState:"Stable",boundedMovement:"No conflicting movement",endCameraState:"Stable",subjectRelation:"Interaction remains readable",timing:"Throughout"}],focusExecutions:[{directorShotId:I.shot,progression:[{order:0,targetKind:"CHARACTER",authorityRefs:[I.character],semanticLabel:"Character",timing:"At action start"},{order:1,targetKind:"PRODUCT",authorityRefs:[I.product],semanticLabel:"Product result",timing:"At completion"}]}],environmentalMotions:[{environmentalMotionId:id(38),semanticMotion:"Subtle ambient fabric movement",affectedAuthorityRefs:[],dominance:"SUPPORTING",timing:"Throughout"}],motionBudget:{policyId:"CORE_BALANCED",policyVersion:1,profileId:"CORE",maxDominantActions:1,maxCameraBehaviors:1,maxEnvironmentalMotions:1,complexityThreshold:4,identitySensitiveProduct:productRequirement==="REQUIRED",riskFactors:[]},physicalConstraints:[{constraintId:I.constraint,semanticConstraint:"Product remains supported",authorityRefs:[I.product],satisfied:true}],
  };
  const qcDecision = options.qcDecision ?? "DISPATCH_ELIGIBLE";
  const qcEvaluation = {
    qcEvaluationId:I.qc,orgId:I.org,workspaceId:I.workspace,storyId:I.story,storyVersionId:I.storyVersion,outlineVersionId:I.outline,scriptVersionId:I.script,handoffId:I.handoff,directorPlanId:I.director,motionPlanId:I.motion,sceneExecutionId:I.sceneExecution,sceneVersionIds:[I.sceneVersion],contractVersion:"ai-story-pre-generation-qc.v1",gateSetVersion:1,providerCapabilityId:"animation-video-generation",providerCapabilityVersion:"seedance-modelark-2026-08-29.v1",productAuthorityIds:[I.product],
    gateResults:AI_STORY_PRE_GENERATION_QC_GATE_ORDER.map((gateId)=>({gateId,gateVersion:1,classification:"HARD_GATE",status:qcDecision==="DISPATCH_BLOCKED"&&gateId==="PROVIDER_COMPILATION_READINESS_GATE"?"BLOCK":"PASS",failedLayer:qcDecision==="DISPATCH_BLOCKED"&&gateId==="PROVIDER_COMPILATION_READINESS_GATE"?"PROVIDER_ADAPTER":null,reasonCode:"CERTIFIED",safeEvidence:["Deterministic fixture"],repairOwner:qcDecision==="DISPATCH_BLOCKED"&&gateId==="PROVIDER_COMPILATION_READINESS_GATE"?"PROVIDER_ADAPTER":"NONE",evaluatedArtifactIds:artifactIds,contractVersion:"ai-story-pre-generation-qc.v1"})),
    dispatchDecision:qcDecision,preDispatchBlocked:qcDecision==="DISPATCH_BLOCKED",providerCallAvoided:qcDecision==="DISPATCH_BLOCKED",estimatedAttemptCostAvoidedUsd:null,sceneFunction:"PRODUCT_USAGE",visualRole:"USAGE_DEMONSTRATION",cameraFamily:options.camera??"LOCKED",motionRiskClass:"LOW",productGrounded:productRequirement==="REQUIRED",profileId:"CORE",qcFingerprint:hash("q"),evaluatedBy:I.evaluator,evaluatedAt:"2026-08-29T10:03:00.000Z",
  };
  qcEvaluation.qcFingerprint=computeAiStoryPreGenerationQcFingerprint(qcEvaluation as any);
  const withoutFingerprint:any = {
    sceneExecutionPackageId:I.package,contractVersion:AI_STORY_SCENE_EXECUTION_PACKAGE_CONTRACT_VERSION,orgId:I.org,workspaceId:I.workspace,campaignId:I.campaign,storyId:I.story,storyVersionId:I.storyVersion,outlineVersionId:I.outline,scriptVersionId:I.script,scriptFingerprint:hash("i"),handoffId:I.handoff,handoffFingerprint:hash("j"),directorPlanId:I.director,directorFingerprint:hash("d"),motionPlanId:I.motion,motionFingerprint:hash("m"),scene,locationAuthority:null,
    castAuthorities:[{reference:scene.castBindings[0],displayName:"Recurring Character",identity:"Stable canonical identity",appearance:"Canonical appearance without static pose",coreContinuityFacts:["Identity persists"],sceneStateFacts:["Focused on the Product"],mustKeep:["Preserve Character appearance authority"]}],
    productAuthorities:[{productAuthorityId:I.product,sourceAssetId:I.productAsset,sourceAssetContentHash:hash("p"),displayName:"Unknown synthetic Product",identityFacts:["Canonical Product identity"],visibleEvidenceGoals:["Show intact completion"],sceneStateFacts:["Held at entry"],mustKeep:["Preserve Product identity"],mustAvoid:["No transformation"],visualIdentityRequirement:productRequirement}],
    directorDirection,motionScenePlan,shotRecipe:null,qcEvaluation,generation:{mode,durationSec:6,ratio:"16:9",resolution:"1080p",watermark:false,cameraMappingRequirement:options.cameraRequired??"REQUIRED"},
    visualReferences:options.withReference===false||productRequirement==="NONE"?[]:[{referenceId:I.reference,assetId:I.productAsset,authorityType:"PRODUCT",authorityId:I.product,authorityClass:productRequirement,semanticBinding:"This reference defines the canonical Product appearance.",selectionPriority:100,firstFrame:true,mediaType:"image/png",uri:"https://cdn.example.com/product.png"}],
    providerBinding:{providerId:"seedance",model:"dreamina-seedance-2-0-260128",modelVersion:"dreamina-seedance-2-0-260128",capabilityContractVersion:AI_STORY_SEEDANCE_CAPABILITY_CONTRACT_VERSION,adapterMappingVersion:AI_STORY_SEEDANCE_MAPPING_VERSION,qcCapabilityVersion:"seedance-modelark-2026-08-29.v1"},
  };
  return {...withoutFingerprint,packageFingerprint:seedanceSceneExecutionPackageFingerprint(withoutFingerprint)};
}

async function envelopeFor(payload: unknown) {
  const uri="memory://seedance-director/package";
  const resolver=createMemorySeedancePayloadResolver({[uri]:payload});
  const envelope=await createExecutionEnvelope({version:"1",envelopeId:I.envelope,payloadReference:uri,tenantId:I.org,workspaceId:I.workspace,executionContext:{executionId:I.execution,correlationId:I.correlation,pipelineRunId:I.pipeline,idempotencyKey:"seedance-director-package",timeoutDeadline:"2026-08-29T11:00:00.000Z",dataHandling:{sensitiveData:false,externalProcessingAllowed:true,providerTrainingAllowed:false},trace:{executionPlanId:I.pipeline,sceneExecutionId:I.sceneExecution}},capabilityId:"animation-video-generation",capabilityVersion:"1.0.0",providerPolicySnapshot:{automaticFallbackEnabled:false},canonicalRequest:{contractVersion:"1",executionIdentity:{executionId:I.execution,tenantId:I.org,workspaceId:I.workspace,campaignId:I.campaign,pipelineRunId:I.pipeline,capabilityId:"animation-video-generation",capabilityVersion:"1.0.0",idempotencyKey:"seedance-director-package",deterministicFingerprint:hash("e")},requestSchemaVersion:"1.0.0",resultSchemaVersion:"1.0.0",normalizedPayloadReference:{uri,contentHash:hash("r"),mediaType:"application/json"},outputSchema:{schemaId:"AnimationVideoResult",schemaVersion:"1.0.0"},contextVersions:{"ai-story-scene-execution-package":"1.0.0"},correlation:{correlationId:I.correlation,pipelineRunId:I.pipeline},timeoutPolicy:{timeoutMs:600000,reconciliationDelayMs:5000},retryPolicy:{maxAttempts:1,initialDelayMs:500,maximumDelayMs:500,backoffMultiplier:1},providerConstraints:{executionLookupRequired:true}},createdAt:"2026-08-29T10:04:00.000Z"});
  return {envelope,resolver};
}

describe("Seedance Director Adapter enrichment",()=>{
  it("compiles a versioned deterministic semantic plan and an unknown open-semantic Action",()=>{const value=compileSceneExecutionPackageForSeedance(packageFixture());expect(value.semanticPlan.sections.map((section)=>section.section)).toHaveLength(19);expect(value.prompt).toContain("phase-aligns");expect(value.prompt).toContain("Start:");expect(value.prompt).toContain("Path:");expect(value.prompt).toContain("End:");expect(value.requestFacts.generateAudio).toBe(false);expect(value.selectedReferences).toHaveLength(1);});
  it("keeps T2V first-class for Cast, Product, and recurring concepts when visual identity is not required",()=>{const value=compileSceneExecutionPackageForSeedance(packageFixture({mode:"TEXT_TO_VIDEO",productRequirement:"NONE"}));expect(value.requestFacts.generationMode).toBe("TEXT_TO_VIDEO");expect(value.selectedReferences).toEqual([]);expect(value.prompt).toContain("Recurring Character");expect(value.prompt).toContain("Unknown synthetic Product");});
  it("never silently changes mode or fabricates references",()=>{expect(()=>compileSceneExecutionPackageForSeedance(packageFixture({mode:"TEXT_TO_VIDEO",productRequirement:"REQUIRED"}))).toThrow(/TEXT_TO_VIDEO/);expect(()=>compileSceneExecutionPackageForSeedance(packageFixture({withReference:false}))).toThrow(/exactly one selected first frame/);});
  it("retains continuity video in the package while excluding it from Provider image selection",()=>{const payload=packageFixture();payload.visualReferences.push({referenceId:id(200),assetId:id(201),authorityType:"OTHER",authorityId:id(202),authorityClass:"OPTIONAL",semanticBinding:"Story continuity motion evidence",selectionPriority:1,firstFrame:false,semanticRole:"STORY_CONTINUITY_REFERENCE",mediaType:"video/mp4",storagePath:`${I.workspace}/library/continuity.mp4`});const {packageFingerprint:_,...input}=payload;payload.packageFingerprint=seedanceSceneExecutionPackageFingerprint(input);const compiled=compileImmutableSeedanceRequest({package:payload as any,sceneExecutionId:I.sceneExecution,compiledAt:"2026-09-01T00:00:00.000Z"});expect(compiled.storyReferenceMappings).toHaveLength(2);expect(compiled.referenceMappings).toHaveLength(1);expect(compiled.storyReferenceMappings?.find((item)=>item.assetId===id(201))).toMatchObject({semanticRole:"STORY_CONTINUITY_REFERENCE",providerEmitted:false,mediaType:"video/mp4"});});
  it("fails closed when non-image media is explicitly assigned a Provider image role",()=>{const payload=packageFixture();payload.visualReferences.push({referenceId:id(203),assetId:id(204),authorityType:"OTHER",authorityId:id(205),authorityClass:"REQUIRED",semanticBinding:"Invalid image projection",selectionPriority:1,firstFrame:false,semanticRole:"PROVIDER_IMAGE_REFERENCE",mediaType:"video/mp4",storagePath:`${I.workspace}/library/not-an-image.mp4`});const {packageFingerprint:_,...input}=payload;payload.packageFingerprint=seedanceSceneExecutionPackageFingerprint(input);expect(()=>compileSceneExecutionPackageForSeedance(payload)).toThrow(/non-image media/);});
  it("records preferred-reference degradation without blocking",()=>{const payload=packageFixture({productRequirement:"PREFERRED",withReference:false});payload.visualReferences=[{referenceId:id(90),assetId:id(91),authorityType:"OTHER",authorityId:id(92),authorityClass:"REQUIRED",semanticBinding:"Explicit first-frame continuity authority",selectionPriority:100,firstFrame:true,uri:"https://cdn.example.com/first.png"}];const {packageFingerprint:_,...input}=payload;payload.packageFingerprint=seedanceSceneExecutionPackageFingerprint(input);const value=compileSceneExecutionPackageForSeedance(payload);expect(value.selectedReferences).toHaveLength(1);expect(value.degradations).toEqual(expect.arrayContaining([expect.objectContaining({code:"PREFERRED_REFERENCE_OMITTED",authorityId:I.product})]));});
  it("keeps supporting images as Story lineage in first-frame I2V",()=>{const payload=packageFixture();payload.visualReferences.push({referenceId:id(100),assetId:id(110),authorityType:"OTHER",authorityId:id(120),authorityClass:"OPTIONAL",semanticBinding:"Supporting visual lineage",selectionPriority:50,firstFrame:false,semanticRole:"STORY_VISUAL_REFERENCE",mediaType:"image/jpeg",uri:"https://cdn.example.com/support.jpg"},{referenceId:id(101),assetId:id(111),authorityType:"OTHER",authorityId:id(121),authorityClass:"OPTIONAL",semanticBinding:"Continuity video lineage",selectionPriority:40,firstFrame:false,semanticRole:"STORY_CONTINUITY_REFERENCE",mediaType:"video/mp4",storagePath:`${I.workspace}/library/continuity.mp4`});const {packageFingerprint:_,...input}=payload;payload.packageFingerprint=seedanceSceneExecutionPackageFingerprint(input);const compiled=compileImmutableSeedanceRequest({package:payload as any,sceneExecutionId:I.sceneExecution,compiledAt:"2026-09-01T00:00:00.000Z"});expect(compiled.storyReferenceMappings).toHaveLength(3);expect(compiled.referenceMappings).toHaveLength(1);expect(compiled.referenceMappings[0]).toMatchObject({assetId:I.productAsset,wireRole:"first_frame"});expect(compiled.storyReferenceMappings?.find((item)=>item.assetId===id(110))).toMatchObject({semanticRole:"STORY_VISUAL_REFERENCE",providerEmitted:false});expect(compiled.storyReferenceMappings?.find((item)=>item.assetId===id(111))).toMatchObject({semanticRole:"STORY_CONTINUITY_REFERENCE",providerEmitted:false});});
  it("rejects an explicit mixed reference-image role in first-frame I2V",()=>{const payload=packageFixture();payload.visualReferences.push({referenceId:id(103),assetId:id(113),authorityType:"OTHER",authorityId:id(123),authorityClass:"OPTIONAL",semanticBinding:"Invalid mixed wire role",selectionPriority:50,firstFrame:false,semanticRole:"PROVIDER_IMAGE_REFERENCE",mediaType:"image/jpeg",uri:"https://cdn.example.com/mixed.jpg"});const {packageFingerprint:_,...input}=payload;payload.packageFingerprint=seedanceSceneExecutionPackageFingerprint(input);expect(()=>compileSceneExecutionPackageForSeedance(payload)).toThrowError(expect.objectContaining({code:"SEEDANCE_FIRST_FRAME_I2V_WIRE_MODE_INVALID"}));});
  it("blocks stale QC, tampering, unsafe required camera mapping, and first-frame cardinality",()=>{expect(()=>compileSceneExecutionPackageForSeedance(packageFixture({qcDecision:"DISPATCH_BLOCKED"}))).toThrow(/QC/);const tampered=packageFixture();tampered.scene.mustKeep.push("tampered");expect(()=>compileSceneExecutionPackageForSeedance(tampered)).toThrow(/fingerprint/);expect(()=>compileSceneExecutionPackageForSeedance(packageFixture({camera:"SMALL_ARC"}))).toThrow(/No certified/);expect(compileSceneExecutionPackageForSeedance(packageFixture({camera:"SMALL_ARC",cameraRequired:"OPTIONAL"})).degradations).toEqual(expect.arrayContaining([expect.objectContaining({code:"OPTIONAL_CAMERA_OMITTED"})]));const noFirst=packageFixture();noFirst.visualReferences[0].firstFrame=false;const {packageFingerprint:___,...input}=noFirst;noFirst.packageFingerprint=seedanceSceneExecutionPackageFingerprint(input);expect(()=>compileSceneExecutionPackageForSeedance(noFirst)).toThrow(/exactly one/);});
  it("serializes only certified ModelArk fields and generic reference roles",async()=>{const payload=packageFixture();const {envelope,resolver}=await envelopeFor(payload);const request=await mapCanonicalEnvelopeToSeedanceRequest({envelope,idempotencyKey:"local-only",model:"dreamina-seedance-2-0-260128",payloadResolver:resolver});expect(request).toMatchObject({model:"dreamina-seedance-2-0-260128",duration:6,ratio:"16:9",resolution:"1080p",generate_audio:false,watermark:false});expect(request.content.filter((item)=>item.type==="image_url")).toEqual([{type:"image_url",image_url:{url:"https://cdn.example.com/product.png"},role:"first_frame"}]);expect(JSON.stringify(request)).not.toMatch(/"role":"(?:character|product|location|environment|style)"/);});
  it("fails closed instead of treating a malformed canonical package as a legacy prompt payload",async()=>{const {envelope,resolver}=await envelopeFor({contractVersion:AI_STORY_SCENE_EXECUTION_PACKAGE_CONTRACT_VERSION,prompt:"unsafe legacy fallback"});await expect(mapCanonicalEnvelopeToSeedanceRequest({envelope,idempotencyKey:"local-only",model:"dreamina-seedance-2-0-260128",payloadResolver:resolver})).rejects.toThrow(/legacy payload fallback is denied/);});
  it("keeps last-frame conditioning outside the certified request surface",async()=>{const {envelope,resolver}=await envelopeFor({prompt:"legacy compatibility payload",durationSec:5,aspectRatio:"9:16",resolution:"720p",assetReferences:[{assetId:I.productAsset,uri:"https://cdn.example.com/last.png",role:"last_frame",mediaType:"image/png"}]});await expect(mapCanonicalEnvelopeToSeedanceRequest({envelope,idempotencyKey:"local-only",model:"dreamina-seedance-2-0-260128",payloadResolver:resolver})).rejects.toThrow(/not certified/);});
  it("keeps the translation matrix explicit and refuses uncertified features",()=>{expect(AI_STORY_SEEDANCE_TRANSLATION_MATRIX).toEqual(expect.arrayContaining([{concept:"first frame",translationClass:"CONDITIONING_MAPPING"},{concept:"multi-shot orchestration",translationClass:"NO_SAFE_MAPPING"},{concept:"audio",translationClass:"NO_SAFE_MAPPING"}]));});
  it("preserves explicit Scene generation authority in compilation and fingerprints it",()=>{
    const t2v=packageFixture({mode:"TEXT_TO_VIDEO",productRequirement:"NONE"});
    t2v.generationAuthority={strategy:"TEXT_TO_VIDEO",referenceSource:"REFERENCE_FREE_T2V",effectiveReferenceIds:[],firstFrameAssetId:null,productVisualIdentityRequirement:"NONE"};
    const {packageFingerprint:_,...t2vInput}=t2v;
    t2v.packageFingerprint=seedanceSceneExecutionPackageFingerprint(t2vInput);
    const t2vRequest=compileImmutableSeedanceRequest({package:t2v as any,sceneExecutionId:I.sceneExecution,compiledAt:"2026-08-29T12:00:00.000Z"});
    expect(t2vRequest.generationAuthority).toEqual(t2v.generationAuthority);
    expect(t2vRequest.referenceMappings).toEqual([]);

    const inherited=packageFixture();
    inherited.generationAuthority={strategy:"PRODUCT_GROUNDED_VIDEO",referenceSource:"STORY_INHERITED",effectiveReferenceIds:[I.productAsset],firstFrameAssetId:I.productAsset,productVisualIdentityRequirement:"REQUIRED"};
    const {packageFingerprint:__,...inheritedInput}=inherited;
    inherited.packageFingerprint=seedanceSceneExecutionPackageFingerprint(inheritedInput);
    const explicit=structuredClone(inherited);
    explicit.generationAuthority={...inherited.generationAuthority,referenceSource:"SCENE_EXPLICIT"};
    const {packageFingerprint:___,...explicitInput}=explicit;
    explicit.packageFingerprint=seedanceSceneExecutionPackageFingerprint(explicitInput);
    const inheritedRequest=compileImmutableSeedanceRequest({package:inherited as any,sceneExecutionId:I.sceneExecution,compiledAt:"2026-08-29T12:00:00.000Z"});
    const repeatedRequest=compileImmutableSeedanceRequest({package:inherited as any,sceneExecutionId:I.sceneExecution,compiledAt:"2026-08-29T12:00:00.000Z"});
    const explicitRequest=compileImmutableSeedanceRequest({package:explicit as any,sceneExecutionId:I.sceneExecution,compiledAt:"2026-08-29T12:00:00.000Z"});
    expect(inheritedRequest.requestFingerprint).toBe(repeatedRequest.requestFingerprint);
    expect(inheritedRequest.requestFingerprint).not.toBe(explicitRequest.requestFingerprint);
  });
});

function freshnessFor(request:any, overrides:Record<string,unknown>={}) { return {qcDispatchEligible:true,commercialAuthorizationValid:true,sceneFingerprint:request.sceneFingerprint,directorFingerprint:request.directorFingerprint,motionFingerprint:request.motionFingerprint,qcFingerprint:request.qcFingerprint,packageFingerprint:request.packageFingerprint,castSnapshotFingerprint:request.castSnapshotFingerprint,locationSnapshotFingerprint:request.locationSnapshotFingerprint,productSnapshotFingerprint:request.productSnapshotFingerprint,sceneSuperseded:false,directorSuperseded:false,motionSuperseded:false,authoritySnapshotsMatch:true,...overrides}; }
function runtimeHarness(request:any, options:{submit?:any;poll?:any;ingestFails?:boolean}={}) { const repository=new InMemoryAiStoryProviderRuntimeRepository();let submitCount=0;const sent:any[]=[];const transport={submit:async({request:wire}:any)=>{submitCount++;sent.push(wire);return options.submit??{kind:"ACCEPTED",providerTaskId:"seedance-task-1"};},poll:async()=>options.poll??{status:"succeeded",artifactUrl:"https://provider.example/result.mp4",usage:{durationSeconds:6},metadata:{resolution:"1080p"}}};const runtime=new AiStoryCompiledRequestWorkerRuntime({repository,transport,assetAccess:{resolveHttpsAsset:async({assetId}:any)=>`https://private.example/access/${assetId}`},mediaIngest:{ingest:async()=>{if(options.ingestFails)throw new Error("fixture ingest failure");return{mediaAssetId:id(180)};}}});return{repository,runtime,sent,get submitCount(){return submitCount;}};}

describe("Compiled request Provider Attempt runtime integration",()=>{
  it("maps an immutable compiled request directly without Worker semantic recompilation",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});const {envelope,resolver}=await envelopeFor(request);const wire=await mapCanonicalEnvelopeToSeedanceRequest({envelope,idempotencyKey:"compiled-runtime",model:"dreamina-seedance-2-0-260128",payloadResolver:resolver,assetAccessResolver:{resolveProviderAccessibleUri:async({assetId})=>`https://private.example/access/${assetId}`}});expect(wire.content[0]).toEqual({type:"text",text:request.compiledPrompt});expect(wire.content[1]).toMatchObject({type:"image_url",role:"first_frame"});expect(wire.generate_audio).toBe(false);});
  it("runs T2V through immutable Attempt, fake submit/poll, media ingestion, and post-QC boundary",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture({mode:"TEXT_TO_VIDEO",productRequirement:"NONE"}) as any,sceneExecutionId:I.sceneExecution,compiledAt:"2026-08-29T12:00:00.000Z"});const h=runtimeHarness(request);const created=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"t2v-authorized",now:"2026-08-29T12:01:00.000Z"});const outcome=await h.runtime.process(created.job,"worker-a");expect(outcome.attempt.status).toBe("POST_GENERATION_QC_PENDING");expect(outcome.postGenerationQcInput?.generationMode).toBe("TEXT_TO_VIDEO");expect(h.sent[0].content.filter((item:any)=>item.type==="image_url")).toHaveLength(0);expect(h.submitCount).toBe(1);});
  it("runs first-frame I2V through the same runtime and preserves exact references",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});const h=runtimeHarness(request);const created=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"i2v-authorized"});const outcome=await h.runtime.process(created.job,"worker-a");expect(outcome.postGenerationQcInput?.generationMode).toBe("FIRST_FRAME_IMAGE_TO_VIDEO");expect(h.sent[0].content.filter((item:any)=>item.type==="image_url")).toEqual([{type:"image_url",image_url:{url:`https://private.example/access/${I.productAsset}`},role:"first_frame"}]);});
  it("converges duplicate Attempt creation and concurrent worker delivery to one submit",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});const h=runtimeHarness(request,{poll:{status:"running"}});const first=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"same-action"});const duplicate=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"same-action"});expect(duplicate.replayed).toBe(true);await Promise.all([h.runtime.process(first.job,"worker-a"),h.runtime.process(first.job,"worker-b")]);expect(h.submitCount).toBe(1);});
  it("persists Provider task identity before poll failure and reconciles without resubmission",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});const repository=new InMemoryAiStoryProviderRuntimeRepository();let submits=0;let polls=0;const runtime=new AiStoryCompiledRequestWorkerRuntime({repository,transport:{submit:async()=>{submits++;return{kind:"ACCEPTED",providerTaskId:"persisted-task"};},poll:async()=>{polls++;if(polls===1)throw new Error("crash after accepted submit");return{status:"running"};}},assetAccess:{resolveHttpsAsset:async()=>"https://private.example/ref"},mediaIngest:{ingest:async()=>({mediaAssetId:id(180)})}});const created=await createAiStoryProviderAttempt({repository,request,freshness:freshnessFor(request),idempotencyKey:"crash-recovery"});await expect(runtime.process(created.job,"worker-a")).rejects.toThrow(/crash/);expect((await repository.getAttempt(created.attempt.providerAttemptId))?.providerTaskId).toBe("persisted-task");await runtime.process(created.job,"worker-b");expect(submits).toBe(1);});
  it("never blindly resubmits an ambiguous submission",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});const h=runtimeHarness(request,{submit:{kind:"AMBIGUOUS"}});const created=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"ambiguous"});expect((await h.runtime.process(created.job,"worker-a")).attempt.status).toBe("RECONCILIATION_REQUIRED");expect((await h.runtime.process(created.job,"worker-b")).providerSubmitted).toBe(false);expect(h.submitCount).toBe(1);});
  it("normalizes moderation/provider failure without media, release, fallback, or retry",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});const h=runtimeHarness(request,{poll:{status:"failed",moderationRejected:true}});const created=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"moderation"});const outcome=await h.runtime.process(created.job,"worker-a");expect(outcome.attempt).toMatchObject({status:"FAILED",failureClass:"PROVIDER_MODERATION_REJECTED",automaticPaidRetry:false,providerFallback:false});expect(outcome.postGenerationQcInput).toBeUndefined();});
  it("keeps Provider success recoverable when private-media ingestion fails",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});const h=runtimeHarness(request,{ingestFails:true});const created=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"ingest-failure"});const outcome=await h.runtime.process(created.job,"worker-a");expect(outcome.attempt).toMatchObject({status:"MEDIA_INGESTION_FAILED",failureClass:"MEDIA_INGESTION_FAILED"});expect(h.submitCount).toBe(1);});
  it("denies stale, QC-blocked, commercially unauthorized, and tampered creation before any Attempt",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution});for(const overrides of [{sceneSuperseded:true},{qcDispatchEligible:false},{commercialAuthorizationValid:false}]){const repository=new InMemoryAiStoryProviderRuntimeRepository();await expect(createAiStoryProviderAttempt({repository,request,freshness:freshnessFor(request,overrides),idempotencyKey:JSON.stringify(overrides)})).rejects.toBeInstanceOf(AiStoryProviderRuntimeError);}const tampered=structuredClone(request);tampered.structuredRequest.duration=4;await expect(createAiStoryProviderAttempt({repository:new InMemoryAiStoryProviderRuntimeRepository(),request:tampered,freshness:freshnessFor(tampered),idempotencyKey:"tampered"})).rejects.toMatchObject({code:"REQUEST_TAMPERED"});});
  it("keeps minimal Worker payload and immutable estimated cost separate from actual usage",async()=>{const request=compileImmutableSeedanceRequest({package:packageFixture() as any,sceneExecutionId:I.sceneExecution,estimatedCost:{currency:"USD",amount:0.42,source:"CONFIGURED_ESTIMATE"}});const h=runtimeHarness(request);const created=await createAiStoryProviderAttempt({repository:h.repository,request,freshness:freshnessFor(request),idempotencyKey:"cost-snapshot"});expect(Object.keys(created.job).sort()).toEqual(["contractVersion","providerAttemptId","sceneExecutionId","workspaceId"].sort());const outcome=await h.runtime.process(created.job,"worker-a");expect(outcome.attempt.estimatedCost.amount).toBe(0.42);expect(outcome.attempt.actualUsage).toEqual({durationSeconds:6});});
});
