import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Sql } from "postgres";
import { AiStorySupportingCastAuthorityService, closeDb } from "@ceo-agent/db";
import { RUN_DB_INTEGRATION, cleanupRlsFixture, createIntegrationSql, getIntegrationDbUrl, seedRlsFixture, withAuthenticatedUser, type RlsTestFixture } from "./helpers/db-integration";

const describeIntegration = RUN_DB_INTEGRATION && getIntegrationDbUrl() ? describe : describe.skip;
const STORY_A="74000000-0000-4000-8000-000000000001",STORY_B="74000000-0000-4000-8000-000000000002",SUPPORTING="74000000-0000-4000-8000-000000000003",EPHEMERAL="74000000-0000-4000-8000-000000000004",SCENE="74000000-0000-4000-8000-000000000005";

const facts=(name:string)=>({displayName:name,identity:`${name} is a Story-local recurring identity.`,storyRole:"unknown-role-fixture",appearance:`${name} wears a silver coat.`,relationships:[],continuityFacts:["May leave and return later in this Story"],visualAssetIds:[] as string[]});

describeIntegration("AI Story Cast scope additive persistence and isolation",()=>{
  let sql:Sql;let fixture:RlsTestFixture;let service:AiStorySupportingCastAuthorityService;
  const scope=(storyId=STORY_A)=>({orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId,actorUserId:fixture.userAId});
  beforeAll(async()=>{sql=createIntegrationSql();fixture=await seedRlsFixture(sql);service=new AiStorySupportingCastAuthorityService();await sql.unsafe(`DO $$ BEGIN CREATE ROLE authenticated NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$; CREATE SCHEMA IF NOT EXISTS auth; CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;`);await sql`insert into ai_stories(id,org_id,workspace_id,campaign_id,title,original_idea,status,created_by) values(${STORY_A}::uuid,${fixture.orgId}::uuid,${fixture.workspaceAId}::uuid,${fixture.campaignAId}::uuid,'Story A','Cast fixture','draft',${fixture.userAId}::uuid),(${STORY_B}::uuid,${fixture.orgId}::uuid,${fixture.workspaceAId}::uuid,${fixture.campaignAId}::uuid,'Story B','Cast fixture','draft',${fixture.userAId}::uuid)`;await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-cast-v1.sql"),"utf8"));await sql.unsafe("GRANT USAGE ON SCHEMA public TO authenticated; GRANT SELECT,INSERT,UPDATE ON ai_story_supporting_characters TO authenticated; GRANT SELECT,INSERT ON ai_story_supporting_character_versions,ai_story_cast_promotions TO authenticated");},30_000);
  afterAll(async()=>{await closeDb();if(!sql)return;await sql`delete from ai_story_cast_promotions where org_id=${fixture.orgId}::uuid`;await sql.begin(async(tx)=>{await tx`delete from ai_story_supporting_character_versions where org_id=${fixture.orgId}::uuid`;await tx`delete from ai_story_supporting_characters where org_id=${fixture.orgId}::uuid`;await tx`delete from ai_story_character_versions where org_id=${fixture.orgId}::uuid`;await tx`delete from ai_story_characters where org_id=${fixture.orgId}::uuid`;});await sql`delete from ai_stories where id in (${STORY_A}::uuid,${STORY_B}::uuid)`;await cleanupRlsFixture(sql,fixture);await sql.end();},30_000);

  it("persists one stable Supporting identity across Story reloads and versions",async()=>{const v1=await service.add(scope(),facts("River"),SUPPORTING,"2026-08-29T13:00:00.000Z");expect((await service.list(scope()))[0]?.supportingCharacterId).toBe(SUPPORTING);const v2=await service.edit(scope(),SUPPORTING,{...facts("River"),continuityFacts:["Returns in Scene 3 with identity intact"]},1,"2026-08-29T13:01:00.000Z");expect(v2.version).toBe(2);expect(v2.supersedesSupportingCharacterVersionId).toBe(v1.supportingCharacterVersionId);expect((await service.history(scope(),SUPPORTING))[0]).toEqual(v1);});
  it("denies cross-Story, cross-Campaign and cross-workspace Supporting references",async()=>{await expect(service.read(scope(STORY_B),SUPPORTING)).rejects.toMatchObject({code:"SUPPORTING_CHARACTER_NOT_FOUND"});await expect(service.read({...scope(),campaignId:fixture.campaignBId},SUPPORTING)).rejects.toMatchObject({code:"CAST_SCOPE_DENIED"});const rows=await withAuthenticatedUser(sql,fixture.userBId,(tx)=>tx<{supporting_character_id:string}[]>`select supporting_character_id from ai_story_supporting_characters where supporting_character_id=${SUPPORTING}::uuid`);expect(rows).toEqual([]);});
  it("records explicit Ephemeral-to-Supporting and Supporting-to-Campaign lineage without rewriting source",async()=>{const ephemeral={scope:"EPHEMERAL_ACTOR" as const,id:EPHEMERAL,storyId:STORY_A,scriptSceneId:SCENE,displayName:"Nova",semanticRole:"one-scene synthetic role",appearance:"Amber jacket",visualIdentityRequirement:"PREFERRED" as const};const first=await service.promoteEphemeralToSupporting(scope(),ephemeral,{...facts("Nova"),appearance:"Amber jacket"},"2026-08-29T13:02:00.000Z");expect(first.source.scope).toBe("EPHEMERAL_ACTOR");expect(first.target.scope).toBe("STORY_SUPPORTING_CHARACTER");const river=await service.read(scope(),SUPPORTING);const second=await service.promoteSupportingToCampaign(scope(),SUPPORTING,{name:river.displayName,identity:river.identity,appearance:river.appearance,personality:"User-authored Campaign personality",emotionalArc:"User-authored Campaign arc",relationships:[],visualAssetIds:[]},"2026-08-29T13:03:00.000Z");expect(second.source.scope).toBe("STORY_SUPPORTING_CHARACTER");expect(second.target.scope).toBe("CAMPAIGN_CHARACTER");expect((await service.read(scope(),SUPPORTING)).fingerprint).toBe(river.fingerprint);});
  it("soft-deletes Supporting identity while preserving immutable history",async()=>{const current=await service.read(scope(),SUPPORTING);await service.delete(scope(),SUPPORTING,current.version,"2026-08-29T13:04:00.000Z");await expect(service.read(scope(),SUPPORTING)).rejects.toMatchObject({code:"SUPPORTING_CHARACTER_NOT_FOUND"});expect((await service.history(scope(),SUPPORTING)).length).toBe(3);});
  it("enables RLS on every durable Cast table and creates no Ephemeral Actor table",async()=>{const rows=await sql<{relname:string;relrowsecurity:boolean}[]>`select relname,relrowsecurity from pg_class where relname in ('ai_story_supporting_characters','ai_story_supporting_character_versions','ai_story_cast_promotions') order by relname`;expect(rows).toHaveLength(3);expect(rows.every((row)=>row.relrowsecurity)).toBe(true);const ephemeralTables=await sql<{count:number}[]>`select count(*)::int count from pg_class where relname='ai_story_ephemeral_actors'`;expect(ephemeralTables[0]?.count).toBe(0);});
});
