import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Sql } from "postgres";
import {
  AiStoryOutlineAuthorityService,
  AiStoryScriptAuthorityService,
  AiStoryScriptDirectorHandoffAuthorityService,
  AiStoryDirectorPlanAuthorityService,
  AiStoryMotionPlanAuthorityService,
  AiStoryPreGenerationQcAuthorityService,
  closeDb,
} from "@ceo-agent/db";
import { buildAiStoryOutlineVersion, buildAiStoryScriptVersion } from "@ceo-agent/shared/server";
import { RUN_DB_INTEGRATION, cleanupRlsFixture, createIntegrationSql, getIntegrationDbUrl, seedRlsFixture, withAuthenticatedUser, type RlsTestFixture } from "./helpers/db-integration";

const describeIntegration = RUN_DB_INTEGRATION && getIntegrationDbUrl() ? describe : describe.skip;
const id=(n:number)=>`62000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;
const I={story:id(1),storyVersion:id(2),unit:id(3),beat:id(4),scene:id(5),entry:id(6),character:id(7),product:id(8)};

describeIntegration("AI Story immutable Script Director handoff persistence",()=>{
  let sql:Sql;let fixture:RlsTestFixture;let handoffA:string;let handoffB:string;let scriptA:string;let scriptB:string;let directorPlanId:string;let motionPlanId:string;let qcEvaluationId:string;
  beforeAll(async()=>{
    sql=createIntegrationSql();fixture=await seedRlsFixture(sql);
    await sql.unsafe(`DO $$ BEGIN CREATE ROLE authenticated NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$; CREATE SCHEMA IF NOT EXISTS auth; CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;`);
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-outline-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-script-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-script-director-handoff-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-director-plan-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-motion-plan-v1.sql"),"utf8"));
    await sql.unsafe(readFileSync(resolve(process.cwd(),"packages/db/sql/ai-story-pre-generation-qc-v1.sql"),"utf8"));
    await sql.unsafe("GRANT USAGE ON SCHEMA public TO authenticated; GRANT SELECT ON workspace_members,ai_story_script_versions,ai_story_script_director_handoffs,ai_story_director_plan_versions,ai_story_motion_plan_versions,ai_story_pre_generation_qc_evaluations TO authenticated; GRANT INSERT,UPDATE ON ai_story_script_director_handoffs,ai_story_director_plan_versions,ai_story_motion_plan_versions TO authenticated; GRANT INSERT ON ai_story_pre_generation_qc_evaluations TO authenticated");
    await sql`insert into ai_stories(id,org_id,workspace_id,campaign_id,title,original_idea,status) values(${I.story}::uuid,${fixture.orgId}::uuid,${fixture.workspaceAId}::uuid,${fixture.campaignAId}::uuid,'Handoff test','Idea','draft')`;
    await sql`insert into ai_story_versions(id,story_id,version_number,structured_content) values(${I.storyVersion}::uuid,${I.story}::uuid,1,${sql.json({title:"Legacy",summary:"",objective:"",targetAudience:"",tone:"",estimatedDuration:"",story:{opening:"",development:"",ending:""},keyMessages:[],cta:"",assetReferences:[],warnings:[]})})`;
    await sql`insert into assets(id,org_id,workspace_id,campaign_id,type,storage_path,status,source,content_hash) values(${I.product}::uuid,${fixture.orgId}::uuid,${fixture.workspaceAId}::uuid,${fixture.campaignAId}::uuid,'product','private/handoff-product.png','ready','campaign_upload',${`sha256:${"b".repeat(64)}`})`;
    const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};
    const outline=buildAiStoryOutlineVersion({storyId:I.story,storyVersionId:I.storyVersion,orgId:fixture.orgId,workspaceId:fixture.workspaceAId,version:1,profile:{profileId:"CORE",profileVersion:1},premise:"A decision needs proof",coreClaim:"Exact product evidence resolves doubt",storyUnits:[{storyUnitId:I.unit,order:0,purpose:"Complete story",summary:"Proof",requiredBeatIds:[I.beat]}],beats:[{id:I.beat,storyUnitId:I.unit,order:0,classification:"MAJOR",name:"Proof",purpose:"Reveal evidence",summary:"Evidence changes the decision",required:true,ownershipPolicy:"EXCLUSIVE",authorityReferences:[{authorityType:"PRODUCT",authorityId:I.product}]}],hooks:[],setupPayoffs:[],requiredSceneOutcomes:[],authorityReferences:[{authorityType:"PRODUCT",authorityId:I.product}],upstreamAuthorityId:`${fixture.campaignAId}:${I.storyVersion}`,supersedesOutlineVersionId:null,createdBy:fixture.userAId,createdAt:"2026-08-28T02:00:00.000Z"});
    const outlines=new AiStoryOutlineAuthorityService();await outlines.propose(scope,outline);await outlines.validate(scope,outline.outlineVersionId);await outlines.approve(scope,outline.outlineVersionId);const frozenOutline=await outlines.freeze(scope,outline.outlineVersionId);
    const makeScript=(version:number,supersedesScriptVersionId:string|null,action:string,createdAt:string)=>buildAiStoryScriptVersion({storyId:I.story,storyVersionId:I.storyVersion,outlineVersionId:outline.outlineVersionId,orgId:fixture.orgId,workspaceId:fixture.workspaceAId,version,profileId:"CORE",profileVersion:1,outlineSourceHash:frozenOutline.sourceHash,scenes:[{scriptSceneId:I.scene,order:0,outlineBeatClaims:[{outlineBeatId:I.beat,claim:"Reveal the verified product detail"}],sceneFunction:"PRODUCT_DETAIL_REVEAL",sceneFunctionRegistryVersion:1,sceneStateIn:[],sceneStateDeltas:[],sceneStateOut:[],entries:[{entryId:I.entry,order:0,type:"ACTION",subjectId:I.product,action,storyEffect:"Evidence resolves doubt",durationRange:{minSeconds:2,maxSeconds:5}}],characterIds:[I.character],locationIds:[],propIds:[],assetIds:[],productAuthorityRefs:[I.product],targetDurationRange:{minSeconds:3,maxSeconds:9},mustKeep:["Exact product"],mustAvoid:["Unsupported claim"],newInformation:["Detail visible"],newEvidence:["Verified product detail"],newActionOutcomes:["Decision changes"],productEvidence:["Verified product detail"]}],authorityReferences:[{authorityType:"CHARACTER",authorityId:I.character},{authorityType:"PRODUCT",authorityId:I.product}],supersedesScriptVersionId,createdBy:fixture.userAId,createdAt});
    const scripts=new AiStoryScriptAuthorityService();const handoffs=new AiStoryScriptDirectorHandoffAuthorityService();
    const first=makeScript(1,null,"The product detail is inspected.","2026-08-28T02:01:00.000Z");scriptA=first.scriptVersionId;await scripts.propose(scope,first);await scripts.validate(scope,scriptA);await scripts.approve(scope,scriptA);await scripts.freeze(scope,scriptA);handoffA=(await handoffs.createFromFrozenScript(scope,scriptA,"2026-08-28T02:02:00.000Z")).handoff.handoffId;
    const second=makeScript(2,scriptA,"The stronger verified detail is inspected.","2026-08-28T02:03:00.000Z");scriptB=second.scriptVersionId;await scripts.propose(scope,second);expect((await handoffs.validate(scope,handoffA)).some(issue=>issue.gate==="STALE_HANDOFF_GATE")).toBe(true);await scripts.validate(scope,scriptB);await scripts.approve(scope,scriptB);await scripts.freeze(scope,scriptB);handoffB=(await handoffs.createFromFrozenScript(scope,scriptB,"2026-08-28T02:04:00.000Z")).handoff.handoffId;
    const director=new AiStoryDirectorPlanAuthorityService();const proposed=await director.propose(scope,{handoffId:handoffB,createdAt:"2026-08-28T02:05:00.000Z",sceneDirections:[{directorSceneId:id(20),scriptSceneId:I.scene,sceneOrder:0,servedScriptSceneFunction:"PRODUCT_DETAIL_REVEAL",sceneVisualRole:"DETAIL_REVEAL",sceneVisualRoleRegistryVersion:1,contextualTreatment:{semanticIntent:"Make the Script-authorized evidence visually legible",supportedActionEntryIds:[I.entry],supportedStateDeltaIndexes:[],physicalPlausibility:"NOT_CONTRADICTED"},shots:[{directorShotId:id(21),order:0,shotPurpose:"SHOW_EVIDENCE",shotPurposeRegistryVersion:1,shotSize:"MACRO",cameraIntent:"Preserve identity while making the evidence readable",cameraFamily:"LOCKED",focusTarget:{kind:"PRODUCT_COMPONENT",authorityRefs:[I.product],semanticLabel:"Verified product detail"},focusProgression:[{kind:"PRODUCT",authorityRefs:[I.product],semanticLabel:"Product"},{kind:"PRODUCT_COMPONENT",authorityRefs:[I.product],semanticLabel:"Verified detail"}],compositionIntent:"DETAIL_ISOLATION",productEmphasis:"DETAIL_EVIDENCE",newAudienceInformation:["The verified detail is visible"],blockingIntents:[],perspectiveChange:"MINIMAL",revealsUnseenProductSurface:false,productIdentityTransformation:false}],newAudienceInformation:["The claim is supported visually"],servedProductEvidence:["Verified product detail"],differentiationRequirement:{comparedToScriptSceneIds:[],dimensions:["PRODUCT_EVIDENCE","FOCUS"],rationale:"Single-scene evidence treatment"}}]});directorPlanId=proposed.directorPlanId;await director.transition(scope,directorPlanId,"VALIDATED");await director.transition(scope,directorPlanId,"APPROVED");await director.transition(scope,directorPlanId,"FROZEN");
    const phase=id(22);const motion=new AiStoryMotionPlanAuthorityService();const motionPlan=await motion.propose(scope,{directorPlanId,createdAt:"2026-08-28T02:06:00.000Z",sceneMotionPlans:[{sceneMotionPlanId:id(23),directorSceneId:id(20),scriptSceneId:I.scene,sceneOrder:0,actionExecutions:[{actionExecutionId:id(24),scriptActionEntryId:I.entry,semanticAction:"The stronger verified detail is inspected.",dominance:"DOMINANT",startState:[{entityId:I.product,property:"CUSTOM",value:"detail-a-visible",exclusive:true},{entityId:I.product,property:"PRODUCT_STATE",value:"identity-intact",exclusive:true}],actionPath:[{phaseId:phase,order:0,semanticPhase:"Bounded lateral reveal progresses from detail A to B",subjectRefs:[I.product],objectRefs:[I.product],stateChanges:[{entityId:I.product,property:"CUSTOM",fromValue:"detail-a-visible",toValue:"detail-b-visible",causalReason:"Inspection reveals the next verified detail"}]}],endState:[{entityId:I.product,property:"CUSTOM",value:"detail-b-visible",exclusive:true},{entityId:I.product,property:"PRODUCT_STATE",value:"identity-intact",exclusive:true}],completionAssertions:[{entityId:I.product,property:"CUSTOM",expectedValue:"detail-b-visible"}],objectInteractions:[],forceResponses:[]}],objectPersistence:[{objectId:I.product,presentAtStart:true,presentAtEnd:true,authorizedRemovalOrTransformation:false,reason:"Exact Product persists"}],blockingExecutions:[],cameraExecutions:[{directorShotId:id(21),cameraFamily:"LOCKED",startCameraState:"Stable detail framing",boundedMovement:"No translation",endCameraState:"Stable detail framing",subjectRelation:"Product remains readable",timing:"Throughout reveal"}],focusExecutions:[{directorShotId:id(21),progression:[{order:0,targetKind:"PRODUCT",authorityRefs:[I.product],semanticLabel:"Product",timing:"Start"},{order:1,targetKind:"PRODUCT_COMPONENT",authorityRefs:[I.product],semanticLabel:"Verified detail",timing:"Completion"}]}],environmentalMotions:[],motionBudget:{policyId:"IDENTITY_SAFE_DETAIL",policyVersion:1,profileId:"CORE",maxDominantActions:1,maxCameraBehaviors:1,maxEnvironmentalMotions:1,complexityThreshold:3,identitySensitiveProduct:true,riskFactors:[]},physicalConstraints:[{constraintId:id(25),semanticConstraint:"Product identity remains intact",authorityRefs:[I.product],satisfied:true}]}]});motionPlanId=motionPlan.motionPlanId;await motion.transition(scope,motionPlanId,"VALIDATED");await motion.transition(scope,motionPlanId,"APPROVED");await motion.transition(scope,motionPlanId,"FROZEN");
    const qc=new AiStoryPreGenerationQcAuthorityService();const evaluation=await qc.evaluate(scope,{motionPlanId,providerCapability:{capabilityId:"animation-video-generation",capabilityVersion:"seedance-adapter.1.0.0",supportedExecutionModes:["FIRST_FRAME_I2V"],supportedReferenceRoles:["PRODUCT_REFERENCE"],supportedTimingStructures:["SINGLE_SCENE"],estimatedAttemptCostUsd:0.35,verified:true},compilationRequest:{sceneExecutionId:id(26),requestedCapabilityId:"animation-video-generation",executionMode:"FIRST_FRAME_I2V",referenceRoles:["PRODUCT_REFERENCE"],timingStructure:"SINGLE_SCENE",providerNeutralInputsComplete:true},evaluatedAt:"2026-08-28T02:07:00.000Z"});qcEvaluationId=evaluation.qcEvaluationId;
  },30000);
  afterAll(async()=>{await closeDb();if(!sql)return;await sql.unsafe("ALTER TABLE ai_story_pre_generation_qc_evaluations DISABLE TRIGGER ai_story_pregen_qc_immutable_v1");await sql`delete from ai_story_pre_generation_qc_evaluations where story_id=${I.story}::uuid`;await sql.unsafe("ALTER TABLE ai_story_pre_generation_qc_evaluations ENABLE TRIGGER ai_story_pregen_qc_immutable_v1");await sql`delete from ai_story_motion_plan_versions where story_id=${I.story}::uuid`;await sql`delete from ai_story_director_plan_versions where story_id=${I.story}::uuid`;await sql`delete from ai_story_script_director_handoffs where story_id=${I.story}::uuid`;await sql`delete from ai_story_script_versions where story_id=${I.story}::uuid`;await sql`delete from ai_story_outline_versions where story_id=${I.story}::uuid`;await sql`delete from assets where id=${I.product}::uuid`;await sql`delete from ai_story_versions where story_id=${I.story}::uuid`;await sql`delete from ai_stories where id=${I.story}::uuid`;await cleanupRlsFixture(sql,fixture);await sql.end();},30000);
  it("stores exact lineage and supersedes stale handoffs without rewriting history",async()=>{const rows=await sql<{handoff_id:string;script_version_id:string;authority_status:string;version:number}[]>`select handoff_id,script_version_id,authority_status,version from ai_story_script_director_handoffs where story_id=${I.story}::uuid order by version`;expect(rows).toEqual([{handoff_id:handoffA,script_version_id:scriptA,authority_status:"SUPERSEDED",version:1},{handoff_id:handoffB,script_version_id:scriptB,authority_status:"CURRENT",version:2}]);});
  it("binds exact product source content and validates current authority",async()=>{const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};const service=new AiStoryScriptDirectorHandoffAuthorityService();const record=await service.read(scope,handoffB);expect(record.handoff.productAuthorityBindings).toEqual([{productAuthorityId:I.product,sourceAssetId:I.product,sourceAssetContentHash:`sha256:${"b".repeat(64)}`,requiredRoles:["PRESENT","EVIDENCE_REQUIRED"]}]);expect(await service.validate(scope,handoffB)).toEqual([]);});
  it("enables RLS and denies cross-workspace reads",async()=>{const [rls]=await sql<{enabled:boolean}[]>`select relrowsecurity enabled from pg_class where oid='ai_story_script_director_handoffs'::regclass`;expect(rls?.enabled).toBe(true);const own=await withAuthenticatedUser(sql,fixture.userAId,tx=>tx<{handoff_id:string}[]>`select handoff_id from ai_story_script_director_handoffs order by version`);expect(own.map(row=>row.handoff_id)).toEqual([handoffA,handoffB]);const cross=await withAuthenticatedUser(sql,fixture.userBId,tx=>tx<{handoff_id:string}[]>`select handoff_id from ai_story_script_director_handoffs`);expect(cross).toEqual([]);});
  it("rejects all frozen handoff content mutation",async()=>{await expect(withAuthenticatedUser(sql,fixture.userAId,tx=>tx`update ai_story_script_director_handoffs set handoff=jsonb_set(handoff,'{sceneHandoffs,0,mustKeep}','[]') where handoff_id=${handoffB}::uuid`)).rejects.toThrow(/immutable/i);});
  it("rejects cross-workspace service authority",async()=>{const service=new AiStoryScriptDirectorHandoffAuthorityService();await expect(service.read({orgId:fixture.orgId,workspaceId:fixture.workspaceBId,campaignId:fixture.campaignBId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userBId},handoffB)).rejects.toThrow(/scope/i);});
  it("persists, validates, approves, and freezes Director authority under tenant RLS",async()=>{const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};const service=new AiStoryDirectorPlanAuthorityService();const value=await service.read(scope,directorPlanId);expect(value.status).toBe("FROZEN");expect((await service.validate(scope,directorPlanId)).filter(issue=>issue.severity==="BLOCK")).toEqual([]);const own=await withAuthenticatedUser(sql,fixture.userAId,tx=>tx<{director_plan_id:string}[]>`select director_plan_id from ai_story_director_plan_versions`);expect(own).toEqual([{director_plan_id:directorPlanId}]);const cross=await withAuthenticatedUser(sql,fixture.userBId,tx=>tx`select director_plan_id from ai_story_director_plan_versions`);expect(cross).toEqual([]);});
  it("makes frozen Director content immutable",async()=>{await expect(withAuthenticatedUser(sql,fixture.userAId,tx=>tx`update ai_story_director_plan_versions set director_plan=jsonb_set(director_plan,'{sceneDirections,0,sceneVisualRole}','\"PACKSHOT\"') where director_plan_id=${directorPlanId}::uuid`)).rejects.toThrow(/immutable/i);});
  it("persists, validates, and freezes Motion authority under tenant RLS",async()=>{const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};const service=new AiStoryMotionPlanAuthorityService();expect((await service.read(scope,motionPlanId)).status).toBe("FROZEN");expect((await service.validate(scope,motionPlanId)).filter(issue=>issue.severity==="BLOCK")).toEqual([]);const own=await withAuthenticatedUser(sql,fixture.userAId,tx=>tx<{motion_plan_id:string}[]>`select motion_plan_id from ai_story_motion_plan_versions`);expect(own).toEqual([{motion_plan_id:motionPlanId}]);const cross=await withAuthenticatedUser(sql,fixture.userBId,tx=>tx`select motion_plan_id from ai_story_motion_plan_versions`);expect(cross).toEqual([]);});
  it("makes frozen Motion content immutable",async()=>{await expect(withAuthenticatedUser(sql,fixture.userAId,tx=>tx`update ai_story_motion_plan_versions set motion_plan=jsonb_set(motion_plan,'{sceneMotionPlans,0,actionExecutions,0,semanticAction}','\"changed\"') where motion_plan_id=${motionPlanId}::uuid`)).rejects.toThrow(/immutable/i);});
  it("persists immutable dispatch authority with exact frozen lineage",async()=>{const scope={orgId:fixture.orgId,workspaceId:fixture.workspaceAId,campaignId:fixture.campaignAId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userAId};const service=new AiStoryPreGenerationQcAuthorityService();const value=await service.assertCurrent(scope,qcEvaluationId);expect(value.dispatchDecision).toBe("DISPATCH_ELIGIBLE");expect(value.providerCallAvoided).toBe(false);expect(value.motionPlanId).toBe(motionPlanId);expect((await service.history(scope,id(26))).map(v=>v.qcEvaluationId)).toEqual([qcEvaluationId]);});
  it("enables QC RLS, denies cross-tenant reads, and rejects evidence mutation",async()=>{const [rls]=await sql<{enabled:boolean}[]>`select relrowsecurity enabled from pg_class where oid='ai_story_pre_generation_qc_evaluations'::regclass`;expect(rls?.enabled).toBe(true);const own=await withAuthenticatedUser(sql,fixture.userAId,tx=>tx<{qc_evaluation_id:string}[]>`select qc_evaluation_id from ai_story_pre_generation_qc_evaluations`);expect(own).toEqual([{qc_evaluation_id:qcEvaluationId}]);const cross=await withAuthenticatedUser(sql,fixture.userBId,tx=>tx`select qc_evaluation_id from ai_story_pre_generation_qc_evaluations`);expect(cross).toEqual([]);await expect(sql`update ai_story_pre_generation_qc_evaluations set dispatch_decision='DISPATCH_BLOCKED' where qc_evaluation_id=${qcEvaluationId}::uuid`).rejects.toThrow(/immutable/i);});
  it("denies cross-workspace QC service authority",async()=>{const service=new AiStoryPreGenerationQcAuthorityService();await expect(service.read({orgId:fixture.orgId,workspaceId:fixture.workspaceBId,campaignId:fixture.campaignBId,storyId:I.story,storyVersionId:I.storyVersion,actorUserId:fixture.userBId},qcEvaluationId)).rejects.toThrow(/scope/i);});
});
