import { describe, expect, it } from "vitest";
import {
  AiStoryScriptVersionSchema, assertAiStoryScriptLifecycleTransition,
  projectLegacyStoryToScriptCompatibility, validateAiStoryScript,
  projectAiStoryScriptSceneHandoffs,
  type AiStoryOutlineVersion, type AiStoryScriptVersion,
} from "@ceo-agent/shared";
import { buildAiStoryOutlineVersion, buildAiStoryScriptVersion, computeAiStoryScriptSourceHash } from "@ceo-agent/shared/server";

const id = (n: number) => `40000000-0000-4000-8000-${n.toString().padStart(12, "0")}`;
const IDS = { org:id(1), workspace:id(2), campaign:id(3), story:id(4), storyVersion:id(5), actor:id(6), unit:id(7), beatA:id(8), beatB:id(9), character:id(10), product:id(11), sceneA:id(12), sceneB:id(13), entryA:id(14), entryB:id(15), subclaim:id(16) };

function frozenOutline(): AiStoryOutlineVersion {
  return { ...buildAiStoryOutlineVersion({
    storyId:IDS.story,storyVersionId:IDS.storyVersion,orgId:IDS.org,workspaceId:IDS.workspace,version:1,
    profile:{profileId:"CORE",profileVersion:1},premise:"Proof changes a decision",coreClaim:"Product evidence earns trust",
    storyUnits:[{storyUnitId:IDS.unit,order:0,purpose:"Complete story",summary:"Question then proof",requiredBeatIds:[IDS.beatA,IDS.beatB]}],
    beats:[
      {id:IDS.beatA,storyUnitId:IDS.unit,order:0,classification:"MAJOR",name:"Introduction",purpose:"Introduce proof need",summary:"The customer needs evidence",required:true,ownershipPolicy:"EXCLUSIVE",authorityReferences:[]},
      {id:IDS.beatB,storyUnitId:IDS.unit,order:1,classification:"MAJOR",name:"Evidence",purpose:"Deliver product proof",summary:"Evidence changes the decision",required:true,ownershipPolicy:"SPLITTABLE",authorityReferences:[{authorityType:"PRODUCT",authorityId:IDS.product}]},
    ],hooks:[],setupPayoffs:[],requiredSceneOutcomes:[],authorityReferences:[{authorityType:"PRODUCT",authorityId:IDS.product}],upstreamAuthorityId:`${IDS.campaign}:${IDS.storyVersion}`,supersedesOutlineVersionId:null,createdBy:IDS.actor,createdAt:"2026-08-28T00:00:00.000Z",
  }),status:"FROZEN",approvedBy:IDS.actor,approvedAt:"2026-08-28T00:01:00.000Z",frozenAt:"2026-08-28T00:02:00.000Z" };
}

function script(): AiStoryScriptVersion {
  const outline=frozenOutline();
  return buildAiStoryScriptVersion({storyId:IDS.story,storyVersionId:IDS.storyVersion,outlineVersionId:outline.outlineVersionId,orgId:IDS.org,workspaceId:IDS.workspace,version:1,profileId:"CORE",profileVersion:1,outlineSourceHash:outline.sourceHash,
    scenes:[
      {scriptSceneId:IDS.sceneA,order:0,outlineBeatClaims:[{outlineBeatId:IDS.beatA,claim:"Establish need for proof"}],sceneFunction:"PRODUCT_INTRODUCTION",sceneFunctionRegistryVersion:1,
       sceneStateIn:[{dimension:"KNOWLEDGE",subjectId:IDS.character,value:"unconvinced"}],sceneStateDeltas:[{dimension:"KNOWLEDGE",subjectId:IDS.character,fromValue:"unconvinced",value:"questioning",reason:"Product claim appears"}],sceneStateOut:[{dimension:"KNOWLEDGE",subjectId:IDS.character,value:"questioning"}],
       entries:[{entryId:IDS.entryA,order:0,type:"ACTION",subjectId:IDS.character,action:"The customer inspects the product label.",storyEffect:"Creates a concrete question",durationRange:{minSeconds:2,maxSeconds:4}}],characterIds:[IDS.character],locationIds:[],propIds:[],assetIds:[],productAuthorityRefs:[IDS.product],targetDurationRange:{minSeconds:3,maxSeconds:8},mustKeep:["The product identity remains exact"],mustAvoid:["Unsupported product claims"],newInformation:["The product claim is visible"],newEvidence:[],newActionOutcomes:["Customer investigates"],productEvidence:[]},
      {scriptSceneId:IDS.sceneB,order:1,outlineBeatClaims:[{outlineBeatId:IDS.beatB,subclaimId:IDS.subclaim,subclaimOrder:0,claim:"Demonstrate verified evidence"}],sceneFunction:"PRODUCT_DETAIL_REVEAL",sceneFunctionRegistryVersion:1,
       sceneStateIn:[{dimension:"KNOWLEDGE",subjectId:IDS.character,value:"questioning"}],sceneStateDeltas:[{dimension:"KNOWLEDGE",subjectId:IDS.character,fromValue:"questioning",value:"convinced",reason:"Evidence resolves the question"}],sceneStateOut:[{dimension:"KNOWLEDGE",subjectId:IDS.character,value:"convinced"}],
       entries:[{entryId:IDS.entryB,order:0,type:"ACTION",subjectId:IDS.product,action:"The verified product detail is compared with the claim.",storyEffect:"Evidence resolves doubt",durationRange:{minSeconds:3,maxSeconds:6}},{entryId:id(17),order:1,type:"DIALOGUE",speakerId:IDS.character,line:"That is the proof I needed.",language:"en",durationRange:{minSeconds:1,maxSeconds:3}},{entryId:id(18),order:2,type:"VO",voiceOwnerId:IDS.character,line:"Evidence earns trust.",narrativePurpose:"State the resolved claim",language:"en",durationRange:{minSeconds:1,maxSeconds:3}}],
       characterIds:[IDS.character],locationIds:[],propIds:[],assetIds:[],productAuthorityRefs:[IDS.product],targetDurationRange:{minSeconds:5,maxSeconds:14},mustKeep:["Verified evidence"],mustAvoid:["New product identity"],newInformation:["The claim is verified"],newEvidence:["Authoritative product detail"],newActionOutcomes:["Customer decides"],productEvidence:["Verified product detail"]},
    ],authorityReferences:[{authorityType:"CHARACTER",authorityId:IDS.character},{authorityType:"PRODUCT",authorityId:IDS.product}],supersedesScriptVersionId:null,createdBy:IDS.actor,createdAt:"2026-08-28T00:03:00.000Z"});
}

const known = new Set([`CHARACTER:${IDS.character}`,`PRODUCT:${IDS.product}`]);

describe("AI Story Script Scene + Beat authority",()=>{
  it("builds deterministic, provider-neutral Script lineage",()=>{const value=script();expect(value.scriptVersionId).toBe(script().scriptVersionId);expect(value.sourceHash).toBe(computeAiStoryScriptSourceHash(value));expect(validateAiStoryScript(value,frozenOutline(),{knownAuthorityReferences:known})).toEqual([]);const serialized=JSON.stringify(value).toLowerCase();for(const forbidden of ["camera","lens","shotsize","providerequest","motionplanner","seedance"])expect(serialized).not.toContain(forbidden);});
  it("enforces Beat claims, speakers, visible ACTION, timing and reference integrity",()=>{const broken=structuredClone(script());broken.scenes[0]!.outlineBeatClaims[0]!.outlineBeatId=id(99);broken.scenes[0]!.entries=[{entryId:IDS.entryA,order:0,type:"DIALOGUE",speakerId:id(98),line:"Unknown",language:"en",durationRange:{minSeconds:20,maxSeconds:30}}];broken.scenes[0]!.targetDurationRange={minSeconds:1,maxSeconds:2};const gates=new Set(validateAiStoryScript(broken,frozenOutline(),{knownAuthorityReferences:known}).map(i=>i.gate));expect(gates).toEqual(expect.objectContaining(new Set(["BEAT_CLAIM_GATE","ACTION_BEAT_PRESENCE_GATE","DIALOGUE_SPEAKER_GATE","TIMING_FEASIBILITY_GATE"])));});
  it("blocks unexplained state resets",()=>{const broken=structuredClone(script());broken.scenes[1]!.sceneStateIn[0]!.value="forgotten";expect(validateAiStoryScript(broken,frozenOutline(),{knownAuthorityReferences:known}).some(i=>i.gate==="STATE_CONTINUITY_GATE")).toBe(true);});
  it("blocks the R4 duplicate-introduction pattern before Director and passes a distinct evidence Scene",()=>{const duplicate=structuredClone(script());duplicate.scenes[1]!.outlineBeatClaims=[{outlineBeatId:IDS.beatA,claim:"Repeat introduction"}];duplicate.scenes[1]!.sceneFunction="PRODUCT_INTRODUCTION";duplicate.scenes[1]!.sceneStateDeltas=[];duplicate.scenes[1]!.newInformation=[];duplicate.scenes[1]!.newEvidence=[];duplicate.scenes[1]!.newActionOutcomes=[];duplicate.scenes[1]!.productEvidence=[];expect(validateAiStoryScript(duplicate,frozenOutline(),{knownAuthorityReferences:known}).some(i=>i.gate==="SCRIPT_SCENE_DUPLICATION_GATE"&&i.severity==="BLOCK")).toBe(true);expect(validateAiStoryScript(script(),frozenOutline(),{knownAuthorityReferences:known})).toEqual([]);});
  it("enforces lifecycle freeze and preserves legacy reads without materialization",()=>{expect(()=>assertAiStoryScriptLifecycleTransition("DRAFT","APPROVED")).toThrow();expect(()=>assertAiStoryScriptLifecycleTransition("DRAFT","VALIDATED")).not.toThrow();expect(()=>assertAiStoryScriptLifecycleTransition("VALIDATED","APPROVED")).not.toThrow();expect(()=>assertAiStoryScriptLifecycleTransition("APPROVED","FROZEN")).not.toThrow();expect(projectLegacyStoryToScriptCompatibility({storyId:IDS.story,storyVersionId:IDS.storyVersion,structuredContent:{title:"Legacy"},dialogue:[],scenePlan:[]})).toMatchObject({kind:"LEGACY_SCRIPT_COMPATIBILITY",scriptVersion:null});});
  it("rejects downstream Director and camera fields at schema boundary",()=>{const value={...script(),scenes:[{...script().scenes[0],cameraIntent:"push in"}]};expect(AiStoryScriptVersionSchema.safeParse(value).success).toBe(false);});
  it("binds typed Supporting and Ephemeral Cast through Dialogue, VO, Action and immutable handoff projection",()=>{const value=script();const fp=`sha256:${"c".repeat(64)}`;const supporting={scope:"STORY_SUPPORTING_CHARACTER" as const,id:IDS.character,storyId:IDS.story,authorityVersionId:id(70),authorityFingerprint:fp,visualIdentityRequirement:"PREFERRED" as const};value.scenes[0]!.castReferences=[supporting];const action=value.scenes[0]!.entries[0]!;if(action.type!=="ACTION")throw new Error("fixture");action.subjectCastReference=supporting;value.scenes[1]!.castReferences=[supporting];for(const entry of value.scenes[1]!.entries){if(entry.type==="DIALOGUE")entry.speakerCastReference=supporting;if(entry.type==="VO")entry.voiceOwnerCastReference=supporting;}const castKnown=new Set([...known,`STORY_SUPPORTING_CHARACTER:${IDS.character}`]);expect(validateAiStoryScript(value,frozenOutline(),{knownAuthorityReferences:castKnown})).toEqual([]);expect(projectAiStoryScriptSceneHandoffs(value)[0]!.castReferences).toEqual([supporting]);});
  it("denies an Ephemeral Actor outside its owning Scene",()=>{const value=script();const ephemeral={scope:"EPHEMERAL_ACTOR" as const,id:IDS.character,storyId:IDS.story,scriptSceneId:IDS.sceneB,displayName:"One Scene actor",semanticRole:"temporary",appearance:"Neutral coat",visualIdentityRequirement:"NONE" as const};value.scenes[0]!.castReferences=[ephemeral];const gates=validateAiStoryScript(value,frozenOutline(),{knownAuthorityReferences:new Set([...known,`EPHEMERAL_ACTOR:${IDS.character}`])}).map((issue)=>issue.gate);expect(gates).toContain("SCRIPT_REFERENCE_INTEGRITY_GATE");});
});
