import { describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  API_RATE_LIMITS,
  CAMPAIGN_BRIEF_ASSIST_ACTIONS,
  CampaignBriefAssistBodySchema,
  cleanOriginalFilename,
  extractAssetContentIntelligence,
  fallbackAssetDisplayName,
  resolveAssetDisplayLabel,
  validateCampaignForCreate,
} from "@ceo-agent/shared";
import { AiSkillError } from "../packages/agents/src/skills/types";
import {
  CampaignBriefAssistSkill,
  CAMPAIGN_BRIEF_ASSIST_SKILL_ID,
} from "../packages/agents/src/skills/campaign-brief-assist/skill";
import {
  AssetDisplayNameSkill,
  ASSET_DISPLAY_NAME_SKILL_ID,
} from "../packages/agents/src/skills/asset-display-name/skill";
import { executeSkill } from "../packages/agents/src/skills/runner/skill-runner";
import { logAiSkillFailure } from "../apps/web/src/lib/ai-skill-log";

const wizardSource = readFileSync(
  resolve("apps/web/src/app/w/[slug]/campaigns/new/page.tsx"),
  "utf8"
);
const briefAssistSource = readFileSync(
  resolve("apps/web/src/components/campaign/CampaignBriefAssistant.tsx"),
  "utf8"
);
const briefLibSource = readFileSync(
  resolve("apps/web/src/lib/campaign-brief-assist.ts"),
  "utf8"
);
const assetLibSource = readFileSync(
  resolve("apps/web/src/lib/asset-auto-name.ts"),
  "utf8"
);
const briefRouteSource = readFileSync(
  resolve("apps/web/src/app/api/campaigns/[id]/brief/assist/route.ts"),
  "utf8"
);

describe("Sprint 0004 remediation — wizard create semantics", () => {
  it("keeps a five-step wizard without Language or a sixth step", () => {
    expect(wizardSource).toContain(
      'const STEPS = ["name", "objective", "assets", "brief", "review"]'
    );
    expect(wizardSource).not.toMatch(/"language"/);
    expect(wizardSource.match(/STEPS = \[[^\]]+\]/)?.[0].split(",").length).toBe(5);
    expect(wizardSource).toContain("PublishingPlatformMultiSelect");
    expect(wizardSource).not.toContain("platformsUnresolvedHint");
  });

  it("Create Campaign uses authoritative Generate path", () => {
    expect(wizardSource).toContain("onCreateCampaign");
    expect(wizardSource).toContain("validateCampaignForCreate");
    expect(wizardSource).toMatch(/\/api\/campaigns\/\$\{id\}\/generate/);
    expect(wizardSource).not.toMatch(/method:\s*"POST"[^;]*\/run/s);
  });

  it("Create Campaign auto-starts pipeline and returns to Campaign Overview", () => {
    const incomplete = validateCampaignForCreate({
      name: "",
      objective: "other",
      objectiveCustom: "",
      outputLanguage: "en",
      subtitleLanguage: "en",
      ctaLanguage: "en",
      hashtagLanguage: "en",
      assetCount: 0,
      storyCount: 0,
    });
    expect(incomplete.ok).toBe(false);

    const complete = validateCampaignForCreate({
      name: "Spring Promo",
      objective: "awareness",
      outputLanguage: "en",
      subtitleLanguage: "en",
      ctaLanguage: "en",
      hashtagLanguage: "en",
      assetCount: 1,
      storyCount: 0,
    });
    expect(complete.ok).toBe(true);
    if (complete.ok) {
      expect(complete.summary.aiGeneration).toBe(true);
    }
    expect(wizardSource).toMatch(/\/api\/campaigns\/\$\{id\}\/generate/);
    expect(wizardSource).toMatch(/router\.push\(`\/w\/\$\{slug\}\/campaigns\/\$\{id\}`\)/);
  });

  it("abandoned draft remains non-generated by create path", () => {
    // Draft create sets idle; Create Campaign path never calls generate.
    const createRoute = readFileSync(
      resolve("apps/web/src/app/api/campaigns/route.ts"),
      "utf8"
    );
    expect(createRoute).toContain('generateStatus: "idle"');
    expect(wizardSource).toMatch(/\/api\/campaigns\/\$\{id\}\/generate/);
  });
});

describe("Sprint 0004 remediation — AI skills architecture", () => {
  it("business feature modules invoke Skills, not provider helpers", () => {
    expect(briefLibSource).toContain("executeSkill");
    expect(briefLibSource).not.toContain("callJsonModel");
    expect(assetLibSource).toContain('executeSkill("asset-display-name"');
    expect(assetLibSource).not.toContain("callJsonModel");
  });

  it("only polish, expand, and shorten are accepted", () => {
    expect(CAMPAIGN_BRIEF_ASSIST_ACTIONS).toEqual(["polish", "expand", "shorten"]);
    expect(
      CampaignBriefAssistBodySchema.safeParse({ action: "rewrite", text: "x" }).success
    ).toBe(false);
    expect(() =>
      CampaignBriefAssistSkill.validateInput({ action: "rewrite", text: "Hello" })
    ).toThrow(AiSkillError);
  });

  it("skill output is schema validated", () => {
    const input = CampaignBriefAssistSkill.validateInput({
      action: "polish",
      text: "Launch spring bouquet",
    });
    const ok = CampaignBriefAssistSkill.normalizeOutput(
      { text: "  Launch the spring bouquet collection. " },
      input,
      {
        json: {},
        usage: { input: 1, output: 2, costUsd: 0.01 },
        provider: "openai",
        model: "gpt-4o-mini",
      }
    );
    expect(ok.text).toBe("Launch the spring bouquet collection.");
    expect(ok.metadata.skillId).toBe(CAMPAIGN_BRIEF_ASSIST_SKILL_ID);

    expect(() =>
      CampaignBriefAssistSkill.normalizeOutput(
        { text: "" },
        input,
        {
          json: {},
          usage: { input: 0, output: 0, costUsd: 0 },
          provider: "openai",
          model: "gpt-4o-mini",
        }
      )
    ).toThrow(AiSkillError);
  });

  it("provider/model details remain outside business modules", () => {
    expect(briefLibSource).not.toMatch(/gpt-4o/);
    expect(assetLibSource).not.toMatch(/gpt-4o/);
    expect(briefLibSource).not.toMatch(/You assist with Campaign Brief/);
  });

  it("executeSkill routes campaign-brief-assist through injectable router", async () => {
    const route = vi.fn().mockResolvedValue({
      json: { text: "Polished brief" },
      usage: { input: 3, output: 4, costUsd: 0.02 },
      provider: "openai",
      model: "gpt-4o-mini",
    });
    const result = await executeSkill(
      "campaign-brief-assist",
      { action: "polish", text: "brief" },
      { routeJsonCompletion: route }
    );
    expect(result.text).toBe("Polished brief");
    expect(route).toHaveBeenCalledOnce();
  });

  it("skill failure maps to a safe application response path", () => {
    expect(briefRouteSource).toContain("logAiSkillFailure");
    expect(briefRouteSource).toContain("AI_UNAVAILABLE");
    expect(briefRouteSource).toContain("BRIEF_ASSIST_FAILED");
    expect(briefRouteSource).toContain("campaignBriefAssist");
    expect(briefRouteSource).not.toContain("uploadUrl");
  });
});

describe("Sprint 0004 remediation — asset naming safety", () => {
  it("uses content metadata when available and falls back for opaque filenames", () => {
    expect(
      extractAssetContentIntelligence({
        contentSummary: "Sunflower graduation bouquet close-up",
      }).available
    ).toBe(true);
    expect(extractAssetContentIntelligence({ codec: "h264" }).available).toBe(false);

    // Without content intelligence, business layer must use cleaned fallback (no AI invent).
    const intelligence = extractAssetContentIntelligence({});
    expect(intelligence.available).toBe(false);
    expect(fallbackAssetDisplayName("IMG_20260722.jpg")).toBe(
      cleanOriginalFilename("IMG_20260722.jpg")
    );
  });

  it("AI naming skill requires content intelligence and validates output", () => {
    expect(() =>
      AssetDisplayNameSkill.validateInput({
        originalFilename: "IMG_1.jpg",
        type: "image",
      })
    ).toThrow(AiSkillError);

    const input = AssetDisplayNameSkill.validateInput({
      originalFilename: "clip.mp4",
      type: "video",
      contentSummary: "Florist wrapping a blue rose bouquet",
    });
    const result = AssetDisplayNameSkill.normalizeOutput(
      { displayName: "Blue Rose Bouquet.mp4" },
      input,
      {
        json: {},
        usage: { input: 1, output: 1, costUsd: 0 },
        provider: "openai",
        model: "gpt-4o-mini",
      }
    );
    expect(result.displayName).toBe("Blue Rose Bouquet");
    expect(result.metadata.skillId).toBe(ASSET_DISPLAY_NAME_SKILL_ID);
  });

  it("manual rename remains authoritative and original filename stays distinct", () => {
    const libraryPatch = readFileSync(
      resolve("apps/web/src/app/api/workspaces/[id]/library/[assetId]/route.ts"),
      "utf8"
    );
    expect(libraryPatch).toContain('displayNameSource: "manual"');
    expect(libraryPatch).toContain("originalFilename");

    const confirm = readFileSync(
      resolve("apps/web/src/app/api/campaigns/[id]/assets/[assetId]/confirm/route.ts"),
      "utf8"
    );
    expect(confirm).toContain('displayNameSource === "manual"');
    expect(confirm).toContain("suggestReadableAssetName");
    expect(confirm).toContain("metadata");

    const namingLib = readFileSync(
      resolve("apps/web/src/lib/asset-auto-name.ts"),
      "utf8"
    );
    expect(namingLib).toContain("extractAssetContentIntelligence");
    expect(namingLib).toContain('executeSkill("asset-display-name"');
    expect(namingLib).toContain('source: "fallback"');

    expect(
      resolveAssetDisplayLabel({
        displayName: "Manual Name",
        originalFilename: "IMG_1.jpg",
      })
    ).toBe("Manual Name");
    expect(fallbackAssetDisplayName("raw_clip_01.mp4")).toBe("Raw Clip 01");
  });
});

describe("Sprint 0004 remediation — brief accept / restore", () => {
  it("keeps proposal separate until Accept and supports single-level restore", () => {
    expect(briefAssistSource).toContain("setProposal");
    expect(briefAssistSource).toContain("acceptProposal");
    expect(briefAssistSource).toContain("restoreSnapshot");
    // Must not auto-apply AI text into the active Brief.
    expect(briefAssistSource).not.toMatch(/setRestoreSnapshot\(previous\);\s*onChange\(data\.text\)/);
    expect(briefAssistSource).toMatch(/setProposal\(data\.text\)/);
    expect(briefAssistSource).toMatch(/onChange\(proposal\)/);
    expect(briefAssistSource).toMatch(/onChange\(restoreSnapshot\)/);
  });

  it("exposes only polish, expand, shorten actions", () => {
    expect(briefAssistSource).toContain('"polish"');
    expect(briefAssistSource).toContain('"expand"');
    expect(briefAssistSource).toContain('"shorten"');
    expect(briefAssistSource).not.toContain("rewrite");
  });
});

describe("Sprint 0004 remediation — review previews and rate limit", () => {
  it("review uses type-specific preview component", () => {
    expect(wizardSource).toContain("ReviewAssetPreview");
    const preview = readFileSync(
      resolve("apps/web/src/components/campaign/ReviewAssetPreview.tsx"),
      "utf8"
    );
    expect(preview).toContain("previewImage");
    expect(preview).toContain("previewVideo");
    expect(preview).toContain("previewAudio");
    expect(preview).toContain("previewPdf");
    expect(preview).toContain("download-url");
  });

  it("brief assist uses dedicated limiter independent of uploadUrl", () => {
    expect(API_RATE_LIMITS.campaignBriefAssist).toBeDefined();
    expect(API_RATE_LIMITS.uploadUrl).toBeDefined();
    expect(API_RATE_LIMITS.campaignBriefAssist).not.toEqual(API_RATE_LIMITS.uploadUrl);
    expect(briefRouteSource).toContain('"campaignBriefAssist"');
  });

  it("logs safe AI failure metadata without prompts or secrets", () => {
    const spy = vi.spyOn(console, "error").mockImplementation(() => undefined);
    logAiSkillFailure({
      correlationId: "corr-1",
      skillId: CAMPAIGN_BRIEF_ASSIST_SKILL_ID,
      action: "polish",
      campaignId: "camp-1",
      code: "PROVIDER_FAILED",
      resultState: "failed",
    });
    expect(spy).toHaveBeenCalledWith(
      "[ai-skill]",
      expect.objectContaining({
        correlationId: "corr-1",
        skillId: CAMPAIGN_BRIEF_ASSIST_SKILL_ID,
        action: "polish",
        campaignId: "camp-1",
        resultState: "failed",
      })
    );
    const logged = spy.mock.calls[0]?.[1] as Record<string, unknown>;
    expect(logged).not.toHaveProperty("prompt");
    expect(logged).not.toHaveProperty("apiKey");
    expect(logged).not.toHaveProperty("payload");
    spy.mockRestore();
  });
});
