CREATE TABLE IF NOT EXISTS ai_story_pre_generation_qc_evaluations(
 qc_evaluation_id uuid PRIMARY KEY,org_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,campaign_id uuid NOT NULL REFERENCES campaigns(id) ON DELETE RESTRICT,story_id uuid NOT NULL REFERENCES ai_stories(id) ON DELETE RESTRICT,story_version_id uuid NOT NULL REFERENCES ai_story_versions(id) ON DELETE RESTRICT,outline_version_id uuid NOT NULL REFERENCES ai_story_outline_versions(outline_version_id) ON DELETE RESTRICT,script_version_id uuid NOT NULL REFERENCES ai_story_script_versions(script_version_id) ON DELETE RESTRICT,handoff_id uuid NOT NULL REFERENCES ai_story_script_director_handoffs(handoff_id) ON DELETE RESTRICT,director_plan_id uuid NOT NULL REFERENCES ai_story_director_plan_versions(director_plan_id) ON DELETE RESTRICT,motion_plan_id uuid NOT NULL REFERENCES ai_story_motion_plan_versions(motion_plan_id) ON DELETE RESTRICT,scene_execution_id uuid NOT NULL,evaluation_version integer NOT NULL CHECK(evaluation_version>0),contract_version text NOT NULL CHECK(contract_version='ai-story-pre-generation-qc.v1'),gate_set_version integer NOT NULL CHECK(gate_set_version>0),provider_capability_id text NOT NULL,provider_capability_version text NOT NULL,dispatch_decision text NOT NULL CHECK(dispatch_decision IN('DISPATCH_ELIGIBLE','DISPATCH_ELIGIBLE_WITH_WARNINGS','DISPATCH_BLOCKED')),qc_fingerprint text NOT NULL CHECK(qc_fingerprint~'^sha256:[0-9a-f]{64}$'),evaluation jsonb NOT NULL,evaluated_by uuid NOT NULL,evaluated_at timestamptz NOT NULL,CONSTRAINT ai_story_pregen_qc_scene_version_unique UNIQUE(scene_execution_id,evaluation_version),CONSTRAINT ai_story_pregen_qc_scene_fingerprint_unique UNIQUE(scene_execution_id,qc_fingerprint)
);
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ai_story_pregen_qc_evaluation_version_positive')THEN ALTER TABLE ai_story_pre_generation_qc_evaluations ADD CONSTRAINT ai_story_pregen_qc_evaluation_version_positive CHECK(evaluation_version>0);END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ai_story_pregen_qc_contract_check')THEN ALTER TABLE ai_story_pre_generation_qc_evaluations ADD CONSTRAINT ai_story_pregen_qc_contract_check CHECK(contract_version='ai-story-pre-generation-qc.v1');END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ai_story_pregen_qc_gate_set_positive')THEN ALTER TABLE ai_story_pre_generation_qc_evaluations ADD CONSTRAINT ai_story_pregen_qc_gate_set_positive CHECK(gate_set_version>0);END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ai_story_pregen_qc_decision_check')THEN ALTER TABLE ai_story_pre_generation_qc_evaluations ADD CONSTRAINT ai_story_pregen_qc_decision_check CHECK(dispatch_decision IN('DISPATCH_ELIGIBLE','DISPATCH_ELIGIBLE_WITH_WARNINGS','DISPATCH_BLOCKED'));END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ai_story_pregen_qc_fingerprint_check')THEN ALTER TABLE ai_story_pre_generation_qc_evaluations ADD CONSTRAINT ai_story_pregen_qc_fingerprint_check CHECK(qc_fingerprint~'^sha256:[0-9a-f]{64}$');END IF;
END $$;
CREATE INDEX IF NOT EXISTS ai_story_pregen_qc_workspace_idx ON ai_story_pre_generation_qc_evaluations(workspace_id,story_id,evaluated_at);ALTER TABLE ai_story_pre_generation_qc_evaluations ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION enforce_ai_story_pregen_qc_immutable_v1()RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Pre-Generation QC evidence is immutable' USING ERRCODE='23514';END $$;
DROP TRIGGER IF EXISTS ai_story_pregen_qc_immutable_v1 ON ai_story_pre_generation_qc_evaluations;CREATE TRIGGER ai_story_pregen_qc_immutable_v1 BEFORE UPDATE OR DELETE ON ai_story_pre_generation_qc_evaluations FOR EACH ROW EXECUTE FUNCTION enforce_ai_story_pregen_qc_immutable_v1();
DROP POLICY IF EXISTS ai_story_pregen_qc_select ON ai_story_pre_generation_qc_evaluations;CREATE POLICY ai_story_pregen_qc_select ON ai_story_pre_generation_qc_evaluations FOR SELECT TO authenticated USING(workspace_id IN(SELECT workspace_id FROM workspace_members WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS ai_story_pregen_qc_insert ON ai_story_pre_generation_qc_evaluations;CREATE POLICY ai_story_pregen_qc_insert ON ai_story_pre_generation_qc_evaluations FOR INSERT TO authenticated WITH CHECK(workspace_id IN(SELECT workspace_id FROM workspace_members WHERE user_id=auth.uid()AND role IN('admin','operator','editor','reviewer')));
